#!/usr/bin/env python3
"""Generate the concrete hierarchical 256-row by 32-column DRAM bank deck."""

from pathlib import Path
import sys


ROWS = 256
COLUMNS = 32
SUBARRAY_ROWS = 16
OUTPUT = Path(__file__).with_name("dram_bank_256x32.cir")


def joined(prefix: str, count: int) -> str:
    return " ".join(f"{prefix}{index}" for index in range(count))


def column_controls() -> str:
    return " ".join(
        f"select{column} selectb{column}" for column in range(COLUMNS)
    )


def generate() -> str:
    bitlines = joined("bit", COLUMNS)
    wordlines = joined("word", ROWS)
    subarray_wordlines = joined("word", SUBARRAY_ROWS)
    lines = [
        "transistor-level 256x32 DRAM bank core",
        "* AUTOGENERATED by generate.py. Supplies and controls are boundary ports.",
        "* The component accepts one-hot wordline and column-select rails; testbench",
        "* drivers are intentionally outside the proved component.",
        "* Coupling and sense are separate phases: restore/restoreb connect the",
        "* bitline pair to the latch, then sensehi/senselo energize the latch.",
        ".subckt dram_sense_amp q qb sensehi senselo",
        "mpq q qb sensehi sensehi psense",
        "mnq q qb senselo senselo nmod",
        "mpqb qb q sensehi sensehi psense",
        "mnqb qb q senselo senselo nmod",
        "cq q 0 300f",
        "cqb qb 0 300f",
        ".ends dram_sense_amp",
        ".subckt tg left right enable enableb vdd",
        "mn left enable right 0 nmod",
        "mp left enableb right vdd pmod",
        ".ends tg",
        ".subckt dram_cell store word bit",
        "maccess store word bit 0 nmod",
        "cstore store 0 30f",
        ".ends dram_cell",
        f".subckt dram_row32 word {bitlines}",
    ]
    lines.extend(
        f"xcell{column} store{column} word bit{column} dram_cell"
        for column in range(COLUMNS)
    )
    lines.extend(
        [
            ".ends dram_row32",
            f".subckt dram_subarray16x32 {subarray_wordlines} {bitlines}",
        ]
    )
    lines.extend(
        f"xrow{row} word{row} {bitlines} dram_row32"
        for row in range(SUBARRAY_ROWS)
    )
    lines.extend(
        [
            ".ends dram_subarray16x32",
            (
                ".subckt dram_column "
                "bit select selectb vdd vpre precharge restore restoreb "
                "sensehi senselo dout writebus"
            ),
            "cbit bit 0 300f",
            "cref ref 0 300f",
            "mpre bit precharge vpre 0 nmod",
            "mpreref ref precharge vpre 0 nmod",
            "xpreq q vpre restoreb restore vdd tg",
            "xpreqb qb vpre restoreb restore vdd tg",
            "xsense q qb sensehi senselo dram_sense_amp",
            "xcouple bit q restore restoreb vdd tg",
            "xcoupleb ref qb restore restoreb vdd tg",
            "xreadmux q dout select selectb vdd tg",
            "xwritemux writebus bit select selectb vdd tg",
            ".ends dram_column",
            (
                ".subckt dram_bank_256x32 "
                "vdd vpre precharge restore restoreb sensehi senselo "
                "write writeb din dout "
                f"{wordlines} {column_controls()}"
            ),
        ]
    )
    for subarray in range(ROWS // SUBARRAY_ROWS):
        first = subarray * SUBARRAY_ROWS
        connections = " ".join(
            f"word{row}" for row in range(first, first + SUBARRAY_ROWS)
        )
        lines.append(
            f"xsub{subarray} {connections} {bitlines} dram_subarray16x32"
        )
    for column in range(COLUMNS):
        lines.append(
            (
                f"xcolumn{column} bit{column} select{column} "
                f"selectb{column} vdd vpre precharge restore restoreb "
                "sensehi senselo dout writebus dram_column"
            )
        )
    lines.append("xwrite din writebus write writeb vdd tg")
    lines.extend(
        [
            ".ends dram_bank_256x32",
            (
                "xbank vdd vpre precharge restore restoreb sensehi senselo "
                f"write writeb din dout {wordlines} {column_controls()} "
                "dram_bank_256x32"
            ),
            ".model nmod nmos (level=1 vto=1 kp=100u lambda=0 is=0)",
            ".model pmod pmos (level=1 vto=-1 kp=50u lambda=0 is=0)",
            ".model psense pmos (level=1 vto=-1 kp=100u lambda=0 is=0)",
            ".end",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    generated = generate()
    if sys.argv[1:] == ["--check"]:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit(
                f"{OUTPUT}: generated deck is stale; run {Path(__file__).name}"
            )
        print(
            f"{OUTPUT}: {ROWS} rows x {COLUMNS} columns, "
            "generated deck is current"
        )
        return
    if sys.argv[1:]:
        raise SystemExit(f"usage: {Path(__file__).name} [--check]")
    OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
