/-
AUTOGENERATED by extractors/python/extract.py — DO NOT EDIT.
source: Examples/tut_01/tut_01.py
sha256: a91c5b4442f70fd2ecfe1f14946120959c282a3a0f1a5ed117373a86f46358fd
-/
import LeanModels

open LeanModels LeanModels.Python

load_program tut_01 from "Examples/tut_01/tut_01.json"

/-! Tutorial 01 (docs/tutorial/01-first-run.md): the whole pipeline on a
three-line file. Non-vacuity checks only — the theorems start in
tutorial 02. -/
#py_check tut_01.double(21) = 42
#py_check tut_01.double(0) = 0
#py_check tut_01.double(-7) = -14
