/-
Examples/system-verilog/alu_div — CV32E40P phase-2 ingestion smoke (sv-0.2).

  cv32e40p_alu_div.sv.json — symbolic envelope of OpenHW CV32E40P
                             `rtl/cv32e40p_alu_div.sv` (checkout
                             6033d2b1be3295ec774d17ac4cf226faacfdeb08),
                             regenerated byte-identically by
      python3.12 extractors/sv/extract.py --top cv32e40p_alu_div \
          rtl/include/cv32e40p_pkg.sv rtl/include/cv32e40p_apu_core_pkg.sv \
          rtl/include/cv32e40p_fpu_pkg.sv rtl/cv32e40p_alu_div.sv \
          -o cv32e40p_alu_div.sv.json
  ingest.lean              — THIS FILE: `load_design_sv2` smoke. The
                             ∀-C_WIDTH ⊨tx crown jewel
                             (`docs/cv32e40p-spec-surface.md` entry 6) needs
                             T-case/T-ops/T-reset/T-select; this file
                             certifies the parametric pipeline under it.

Passed `PDesign.crossCheck` at load (defaults 32/6: every declared width,
localparam, and top-level generate count agrees with slang's `resolved`
metadata — the load-time differential; a mismatch refuses the load).

What the pins certify, at (C_WIDTH, C_LOG_WIDTH) = (32,6) and (8,3):
* binder encoding: `cv32e40p_alu_div : (C_WIDTH : Nat) → (C_LOG_WIDTH : Nat)
  → Design` — TWO binders in declaration order (the RTL leaves C_LOG_WIDTH
  an independent parameter rather than deriving it; the spec phase will
  carry `C_LOG_WIDTH = $clog2(C_WIDTH)+1`-style hypotheses honestly);
* the enum state type (`IDLE/DIVIDE/FINISH`, anonymous `e$16`) ingests as
  a 2-bit `EnumType` with its member table as data;
* the whole C_WIDTH-wide datapath scales with the parameters
  (41 declarations, ports first);
* the bit-swap generate family (`gen_bit_swapping`) expands to C_WIDTH
  per-index items: 18 + 32 = 50 processes at 32, 18 + 8 = 26 at 8;
* in-tier constructs RUN under the untouched M0 semantics (the comb settle
  evaluates the in-tier assigns/AlwaysComb) and the first out-of-tier node
  reached — a bit-select value, T-select — stops the run LOUDLY.
-/
import LeanModels.Sv.Ingest2
import LeanModels

namespace Examples.«system-verilog».alu_div.ingest

open LeanModels.Sv

load_design_sv2 cv32e40p_alu_div from "Examples/system-verilog/alu_div/cv32e40p_alu_div.sv.json"

/-! ## The family surface -/

-- Two SV parameters → two Nat binders, declaration order.
#guard cv32e40p_alu_div.pdesign.params.map (·.name) == ["C_WIDTH", "C_LOG_WIDTH"]
#guard cv32e40p_alu_div.pdesign.localParams == []

-- The FSM enum (anonymous in source, slang name e$16) is data: 2-bit base,
-- ordered member table, never folded away at parse time.
#guard cv32e40p_alu_div.pdesign.enums.map
        (fun e => (e.name, e.members.map fun m => (m.name, m.value)))
      == [("e$16", [("IDLE", .int 0), ("DIVIDE", .int 1), ("FINISH", .int 2)])]

-- 41 declarations, ports first (12 ports: 10 in + 2 out), parameter-independent
-- name/direction surface.
#guard cv32e40p_alu_div.pdesign.decls.length == 41
#guard (cv32e40p_alu_div 32 6).inputNames ==
  #["Clk_CI", "Rst_RBI", "OpA_DI", "OpB_DI", "OpBShift_DI", "OpBIsZero_SI",
    "OpBSign_SI", "OpCode_SI", "InVld_SI", "OutRdy_SI"]
#guard (cv32e40p_alu_div 32 6).outputNames == #["OutVld_SO", "Res_DO"]

-- The starter lemma consumes the loaded design, ∀ args ∀ fuel.
example {args : List Int} {F : Nat} {m : Design}
    (h : cv32e40p_alu_div.pdesign.instantiate args F = .ok m) : m.WFNames :=
  instantiate_WFNames h (by decide)

/-! ## Two parameter points of one family -/

private def widthOf (d : Design) (n : String) : Option Nat :=
  (d.decls.find? (·.name == n)).map (·.width)

-- (32, 6): the core's instantiation — datapath C_WIDTH wide, counter
-- C_LOG_WIDTH wide, FSM state at the enum's 2-bit base width.
#guard [widthOf (cv32e40p_alu_div 32 6) "OpA_DI",
        widthOf (cv32e40p_alu_div 32 6) "OpBShift_DI",
        widthOf (cv32e40p_alu_div 32 6) "ResReg_DP",
        widthOf (cv32e40p_alu_div 32 6) "Cnt_DP",
        widthOf (cv32e40p_alu_div 32 6) "State_SP",
        widthOf (cv32e40p_alu_div 32 6) "Res_DO"]
      == [some 32, some 6, some 32, some 6, some 2, some 32]

-- (8, 3): same family, every width follows the parameters (enum width
-- does not — the state type is parameter-independent, honestly).
#guard [widthOf (cv32e40p_alu_div 8 3) "OpA_DI",
        widthOf (cv32e40p_alu_div 8 3) "OpBShift_DI",
        widthOf (cv32e40p_alu_div 8 3) "ResReg_DP",
        widthOf (cv32e40p_alu_div 8 3) "Cnt_DP",
        widthOf (cv32e40p_alu_div 8 3) "State_SP"]
      == [some 8, some 3, some 8, some 3, some 2]

-- gen_bit_swapping expands to one item per bit index: 18 module-level
-- processes + C_WIDTH generate iterations.
#guard (cv32e40p_alu_div 32 6).processes.size == 50
#guard (cv32e40p_alu_div 8 3).processes.size == 26

/-! ## Loudness ledger (the honest part)

The envelope now carries the selects / `$signed` casts / reductions /
`case` / async-reset process as semantic-tier sv-0.2 nodes. The **M0**
`Design` still refuses the first one reached loudly (`T2:*`); the
**semantic tier** (`Design2`, next section) executes the whole divider. -/

#guard (cv32e40p_alu_div 32 6).hasUnsupported
#guard run (cv32e40p_alu_div 32 6) σ_src 256 [[]]
        == .unsupported "unsupported expression 'T2:BitSel'"
#guard run (cv32e40p_alu_div 8 3) σ_src 256 [[]]
        == .unsupported "unsupported expression 'T2:BitSel'"

-- Bad parameters are loud, never wrong.
#guard cv32e40p_alu_div.pdesign.instantiate [32]
        == .unsupported "parameter arity: got 1, want 2"

/-! ## Phase-2 acceptance: the whole serial divider EXECUTES

`instantiate2` lowers the same `pdesign` fully in-tier at both parameter
points (selects, `$signed`-marked comparisons, reductions, the FSM
`case`, and the `@(posedge Clk_CI or negedge Rst_RBI)` async reset all
run). The replay below is the differential harness case `alu_div_w8`
(`harness/sv/cases2.json`) — the exact 18-cycle dual-transaction trace,
green vs **Xcelium and Icarus** on the identical RTL source: an async
reset cycle, a UDIV transaction (OpA=7, OpB=200 pre-shifted by 1 →
quotient 0 after the 2-cycle serial loop), then a UREM transaction
(7 mod 200 = 7), with the `InVld/OutVld` handshake observable. -/

#guard (cv32e40p_alu_div.pdesign.instantiate2 [8, 3]).toOption.map
        (·.hasUnsupported) == some false
#guard (cv32e40p_alu_div.pdesign.instantiate2 [32, 6]).toOption.map
        (·.hasUnsupported) == some false

private def divIn (a b : Nat) (shift : Nat) (op : Nat) (vld : Nat) : SvState :=
  [("Rst_RBI", LVec.lit "1"), ("OpA_DI", LVec.ofNat 8 a),
   ("OpB_DI", LVec.ofNat 8 b), ("OpBShift_DI", LVec.ofNat 4 shift),
   ("OpBIsZero_SI", LVec.lit "0"), ("OpBSign_SI", LVec.lit "0"),
   ("OpCode_SI", LVec.ofNat 2 op), ("InVld_SI", LVec.ofNat 1 vld),
   ("OutRdy_SI", LVec.lit "1")]

private def divStim : List SvState :=
  [-- CYCLE 0: async reset asserted (Rst_RBI = 0)
   [("Rst_RBI", LVec.lit "0"), ("OpA_DI", LVec.ofNat 8 0),
    ("OpB_DI", LVec.ofNat 8 0), ("OpBShift_DI", LVec.ofNat 4 0),
    ("OpBIsZero_SI", LVec.lit "0"), ("OpBSign_SI", LVec.lit "0"),
    ("OpCode_SI", LVec.ofNat 2 0), ("InVld_SI", LVec.lit "0"),
    ("OutRdy_SI", LVec.lit "1")],
   divIn 7 200 1 0 1,                     -- CYCLE 1: UDIV 7 / (200>>… )
   [("InVld_SI", LVec.lit "0")], [], [], [], [], [],
   divIn 7 200 1 2 1,                     -- CYCLE 8: UREM 7 mod 200
   [("InVld_SI", LVec.lit "0")], [], [], [], [], [], [], [], []]

#guard (Res.toOption (run2 (cv32e40p_alu_div.pdesign.instantiateD2 [8, 3])
          σ_src 2000 divStim)).map
        (fun tr => tr.map fun st =>
          (SvState.showSignal st "OutVld_SO", SvState.showSignal st "Res_DO"))
      == some [
        ("1", "00000000"),  -- c0  reset: IDLE, OutVld high, result clear
        ("0", "00000000"),  -- c1  UDIV accepted
        ("0", "00000000"),  -- c2  serial loop
        ("1", "00000000"),  -- c3  done: 7/200 = 0
        ("1", "00000000"), ("1", "00000000"), ("1", "00000000"), ("1", "00000000"),
        ("0", "00000111"),  -- c8  UREM accepted (comb result path shows 7)
        ("0", "00000111"),  -- c9  serial loop
        ("1", "00000111"),  -- c10 done: 7 mod 200 = 7
        ("1", "00000111"), ("1", "00000111"), ("1", "00000111"), ("1", "00000111"),
        ("1", "00000111"), ("1", "00000111"), ("1", "00000111")]

end Examples.«system-verilog».alu_div.ingest
