#!/usr/bin/env python3
"""Testbench generator for the SV phase-2 (semantic tier) differential
harness (python3 / 3.9+).

Unlike M0's gen_tb.py, port widths are NOT read from the envelope (they are
symbolic there): the Lean runner (`runner2.lean`) elaborates the design at
the case's parameter values and reports `PORT <name> <dir> <width>` lines —
the single source of truth for widths — which diff_test2.py passes in here.

Same observation conventions as M0: clock period 3 (inputs at 3k, posedge
3k+1, negedge 3k+2), stimulus applied while the clock is low, sampling in
`always @(negedge clk)` printing `CYCLE <k> <name>=%b ...` with hierarchical
`dut.<name>` references. Parameter overrides are emitted on the DUT
instantiation (`#(.LEN(32))`). The case may name its clock port (`"clock"`,
default `"clk"`); a DUT without that port still gets a pacing TB clock.
"""


class TbError(Exception):
    pass


def _decl(name, width):
    if width == 1:
        return "  logic %s;" % name
    return "  logic [%d:0] %s;" % (width - 1, name)


def generate_tb2(mod_name, ports, case):
    """ports: list of (name, dir, width) from the runner's PORT lines."""
    port_width = {p[0]: p[2] for p in ports}
    in_names = {p[0] for p in ports if p[1] == "in"}
    clock = case.get("clock", "clk")
    params = case.get("params", {}) or {}

    signals = case["signals"]
    stimulus = case["stimulus"]

    for k, entry in enumerate(stimulus):
        for name, bits in entry.items():
            if name not in in_names:
                raise TbError("cycle %d: stimulus name '%s' is not an input port"
                              % (k, name))
            if name == clock:
                raise TbError("cycle %d: the clock is driven by the TB" % k)
            if len(bits) != port_width[name]:
                raise TbError("cycle %d: stimulus '%s' width %d != port width %d"
                              % (k, name, len(bits), port_width[name]))
            if any(c not in "01xz" for c in bits):
                raise TbError("cycle %d: stimulus '%s' has bad digit in %r"
                              % (k, name, bits))

    lines = []
    lines.append("// Auto-generated by harness/sv/gen_tb2.py -- case '%s', module '%s'."
                 % (case["name"], mod_name))
    lines.append("// Canonical output: 'CYCLE <k> <name>=<binary>...' per cycle,")
    lines.append("// sampled at negedge (after the posedge timestep's NBA commit).")
    lines.append("module tb;")
    lines.append("  logic %s = 1'b0;  // decl init: no time-0 transition" % clock)
    for name, _dir, width in ports:
        if name == clock:
            continue
        lines.append(_decl(name, width))
    if params:
        ovr = ", ".join(".%s(%d)" % (k, v) for k, v in params.items())
        head = "  %s #(%s) dut (" % (mod_name, ovr)
    else:
        head = "  %s dut (" % mod_name
    conns = ", ".join(".%s(%s)" % (p[0], p[0]) for p in ports)
    lines.append(head + conns + ");")
    lines.append("")
    lines.append("  integer cycle = 0;")
    fmt = "CYCLE %0d " + " ".join("%s=%%b" % n for n in signals)
    args = ", ".join(["cycle"] + ["dut.%s" % n for n in signals])
    lines.append("  always @(negedge %s) begin" % clock)
    lines.append('    $display("%s", %s);' % (fmt, args))
    lines.append("    cycle = cycle + 1;")
    lines.append("  end")
    lines.append("")
    lines.append("  initial begin")
    for k, entry in enumerate(stimulus):
        lines.append("    // cycle %d" % k)
        for name, bits in entry.items():
            lines.append("    %s = %d'b%s;" % (name, len(bits), bits))
        lines.append("    #1 %s = 1'b1;" % clock)
        lines.append("    #1 %s = 1'b0;" % clock)
        lines.append("    #1;")
    lines.append("    $finish;")
    lines.append("  end")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"
