#!/usr/bin/env python3
"""Testbench generator for the SV M0 differential harness (python3 / 3.9+).

Given an extractor envelope
(Examples/system-verilog/<example>/<example>.sv.json — the ports are
read from here, so the TB is generated against exactly what the Lean side
ingests) and one case from harness/sv/cases.json, emits a self-checkingly
*observable* testbench:

  * drives a clock (period 3 time units: inputs at 3k, posedge at 3k+1,
    negedge at 3k+2) — connected to the DUT's `clk` input if it has one;
  * applies each cycle's stimulus values while the clock is low, one time
    unit before the posedge (an input absent from a cycle's entry HOLDS its
    previous value, matching the Lean scheduler's `applyInputs`);
  * samples in an `always @(negedge clk)` block — i.e. after the posedge
    timestep's NBA commit has settled, per the design contract — printing
    the canonical line `CYCLE <k> <name>=%b ...` with the case's signals in
    order; sampled signals are referenced hierarchically (`dut.<name>`) so
    internal signals (race_blk/swap_nba `a`,`b`) work like ports.

The clock variable is *declaration-initialized* to 0 (`logic clk = 1'b0;`):
declaration initializers produce no time-0 transition, so the x->0 change
cannot fire a spurious negedge sample.

CLI (for eyeballing a TB): python3 gen_tb.py <envelope.sv.json> <cases.json> <case_name>
"""

import json
import sys


class TbError(Exception):
    pass


def _module_of(envelope):
    modules = envelope["design"]["modules"]
    if len(modules) != 1:
        raise TbError("expected exactly one module in the envelope, got %d" % len(modules))
    return modules[0]


def _decl(name, width):
    if width == 1:
        return "  logic %s;" % name
    return "  logic [%d:0] %s;" % (width - 1, name)


def generate_tb(envelope, case):
    """Return the testbench source text (str) for one case."""
    mod = _module_of(envelope)
    mod_name = mod["name"]
    ports = [p for p in mod["ports"]]
    for p in ports:
        if p.get("kind") != "Port":
            raise TbError("module '%s' has an unsupported port node" % mod_name)
    in_ports = [p for p in ports if p["dir"] == "in"]
    port_width = {p["name"]: p["width"] for p in ports}
    in_names = {p["name"] for p in in_ports}
    has_clk = "clk" in in_names

    signals = case["signals"]
    stimulus = case["stimulus"]

    # Validate the stimulus against the envelope's ports (the Lean runner
    # performs the identical checks against the ingested Design).
    for k, entry in enumerate(stimulus):
        for name, bits in entry.items():
            if name not in in_names:
                raise TbError("cycle %d: stimulus name '%s' is not an input port" % (k, name))
            if name == "clk":
                raise TbError("cycle %d: the clock is driven by the TB, not the stimulus" % k)
            if len(bits) != port_width[name]:
                raise TbError("cycle %d: stimulus '%s' width %d != port width %d"
                              % (k, name, len(bits), port_width[name]))
            if any(c not in "01xz" for c in bits):
                raise TbError("cycle %d: stimulus '%s' has bad digit in %r" % (k, name, bits))

    lines = []
    lines.append("// Auto-generated by harness/sv/gen_tb.py -- case '%s', module '%s'."
                 % (case["name"], mod_name))
    lines.append("// Canonical output: one 'CYCLE <k> <name>=<binary>...' line per cycle,")
    lines.append("// sampled at negedge (after the posedge timestep's NBA commit).")
    lines.append("module tb;")
    lines.append("  logic clk = 1'b0;  // decl init: no time-0 transition, no spurious negedge")
    for p in ports:
        if p["name"] == "clk":
            continue
        lines.append(_decl(p["name"], p["width"]))
    conns = ", ".join(".%s(%s)" % (p["name"], p["name"]) for p in ports)
    lines.append("  %s dut (%s);" % (mod_name, conns))
    lines.append("")
    lines.append("  integer cycle = 0;")
    fmt = "CYCLE %0d " + " ".join("%s=%%b" % n for n in signals)
    args = ", ".join(["cycle"] + ["dut.%s" % n for n in signals])
    lines.append("  always @(negedge clk) begin")
    lines.append('    $display("%s", %s);' % (fmt, args))
    lines.append("    cycle = cycle + 1;")
    lines.append("  end")
    lines.append("")
    lines.append("  initial begin")
    for k, entry in enumerate(stimulus):
        lines.append("    // cycle %d" % k)
        for name, bits in entry.items():
            lines.append("    %s = %d'b%s;" % (name, len(bits), bits))
        lines.append("    #1 clk = 1'b1;")
        lines.append("    #1 clk = 1'b0;")
        lines.append("    #1;")
    lines.append("    $finish;")
    lines.append("  end")
    lines.append("endmodule")
    # Purely combinational DUTs (adder, xsel) have no clk port: the TB clock
    # still paces the cycles and the negedge sampler; it just isn't connected
    # (has_clk only affects the port-connection list built above).
    _ = has_clk
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) != 4:
        sys.stderr.write("usage: python3 gen_tb.py <envelope.sv.json> <cases.json> <case_name>\n")
        return 2
    with open(argv[1]) as f:
        envelope = json.load(f)
    with open(argv[2]) as f:
        cases = json.load(f)
    matches = [c for c in cases["cases"] if c["name"] == argv[3]]
    if not matches:
        sys.stderr.write("no case named '%s'\n" % argv[3])
        return 1
    sys.stdout.write(generate_tb(envelope, matches[0]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
