/-
AUTOGENERATED by extractors/python/extract.py — DO NOT EDIT.
source: Examples/python/fib.py
sha256: 0221d67f8c689ff42ba430cef8f2ac4de9fdeb89cf1184ea0e558feac216a04b
-/
import LeanModels

open LeanModels LeanModels.Python

load_program fib from "Examples/python/fib.json"

/-! Non-vacuity: concrete runs in surface syntax (`#py_check`,
Surface.lean — fixed generous fuel; minimal-fuel pinning retired). -/
#py_check fib(10) = 55
#py_check fib(0) = 0
#py_check fib(1) = 1

/-- Mathematical Fibonacci: `0, 1, 1, 2, 3, 5, …`. -/
def fibSpec : Nat → Int
  | 0 => 0
  | 1 => 1
  | n + 2 => fibSpec (n + 1) + fibSpec n

#guard fibSpec 10 == 55

set_option warning.simp.varHead false in
/-- **Total correctness**, by strong induction on the mathematical argument
(never on fuel): `fib(k)` terminates and returns `fibSpec k` — stated on
the typed surface (`ToVal Nat` marshals `k`; no `Val`, no fuel). The base
cases are straight-line runs (`py_prove`); in the step case `py_lift` puts
the two IH runs in fuel-threshold form (`CallsTo.at_least`, i.e. FuelMono),
so a single symbolic execution of the body closes the goal by conditional
rewriting. -/
theorem fib_total (k : Nat) : fib(k) ==> fibSpec k := by
  induction k using Nat.strongRecOn with
  | ind k ih =>
    match k, ih with
    | 0, _ => py_prove [fib, fibSpec]
    | 1, _ => py_prove [fib, fibSpec]
    | k + 2, ih =>
      -- `py_lift`: the IHs in threshold form, valid at EVERY fuel ≥ f₁/f₂ —
      -- the final conditional rewrite discharges the ≥ side conditions by
      -- omega, so no exact-offset bookkeeping is needed anywhere below.
      py_lift ⟨f₁, h₁⟩ := ih (k + 1) (by omega) with [fib]
      py_lift ⟨f₂, h₂⟩ := ih k (by omega) with [fib]
      refine ⟨f₁ + f₂ + 32, ?_⟩   -- any generous slack works
      rw [callFunction.eq_2]
      py_simp [fib, show ¬((k : Int) + 2 < 2) by omega,
               show (k : Int) + 2 - 1 = ((k + 1 : Nat) : Int) by omega]
      simp (disch := omega) only [h₁, h₂]
      py_simp [fibSpec]

set_option warning.simp.varHead false in
/-- `fib(n)` computes the Fibonacci numbers for `n ≥ 0`: any successful
run, at any fuel, yields exactly `.int (fibSpec n.toNat)`. A determinism
corollary of `fib_total` — one `py_corollary` (Surface.lean), instantiated
at `n.toNat` because the total theorem is `Nat`-indexed; the tactic's
built-in `Int.toNat_of_nonneg` bridge (discharged by `hn`) aligns the
marshalled argument. -/
@[spec] theorem fib_spec (n : Int) (hn : 0 ≤ n) {fuel : Nat} {r : Val}
    (h : callFunction fib "fib" #[.int n] fuel = .ok r) :
    r = .int (fibSpec n.toNat) := by
  py_corollary [fib_total n.toNat]

set_option warning.simp.varHead false in
/-- The typed surface form: `fib(n)` relationally yields the mathematical
Fibonacci numbers — no `Val`, no fuel in the statement. -/
@[spec] theorem fib_correct (n r : PyInt) (hn : 0 ≤ n) (h : fib(n) ⇓ r) :
    r = fibSpec n.toNat := by
  py_corollary [fib_total n.toNat]
