/-
AUTOGENERATED by extractors/python/extract.py — DO NOT EDIT.
source: Examples/python/tut_04.py
sha256: 1875c112786391c6a31041bd5e4ec85d35675b3a2a7b62549beb4836b885c97d
-/
import LeanModels

open LeanModels LeanModels.Python

load_program tut_04 from "Examples/python/tut_04.json"

/-! Tutorial 04 (docs/tutorial/04-loops.md): the worked exercise —
factorial by loop, proved end-to-end with `py_begin`/`py_loop`. -/
#py_check tut_04.fact(5) = 120
#py_check tut_04.fact(1) = 1
#py_check tut_04.fact(0) = 1
#py_check tut_04.fact(-2) = 1

/-- Mathematical factorial: `1, 1, 2, 6, 24, 120, …` — the spec-side
model, `Int`-valued so it lands where the marshalled result lives. -/
def factSpec : Nat → Int
  | 0 => 1
  | n + 1 => (n + 1 : Int) * factSpec n

#guard factSpec 5 == 120

/-- The unfolding step of `factSpec` in the exact `Int` shape the loop
invariant produces: for `1 ≤ i`, `factSpec i.toNat` peels off one factor
`i`. `grind` consumes this in the invariant-preservation goal. -/
theorem factSpec_step (i : Int) (hi : 1 ≤ i) :
    factSpec i.toNat = i * factSpec (i - 1).toNat := by
  have h : i.toNat = (i - 1).toNat + 1 := by omega
  rw [h, factSpec]
  congr 1
  omega

/-- Total correctness for `n ≥ 0`: `fact(n)` terminates and returns `n!`
— in clause form (LoopTactic.lean). Invariant: `r` holds the factorial
of everything already multiplied in (`r = factSpec (i-1).toNat`), plus
the range `1 ≤ i ≤ n + 1`; measure: iterations left, `(n + 1 - i)`.
Residual goals: the exit algebra (`hcont` + range force `i' = n + 1`,
then `hinv3` *is* the claim), and preservation/decrease/initial all fall
to `grind` armed with `factSpec`'s equations and `factSpec_step`. -/
theorem fact_total (n : PyInt) (hn : 0 ≤ n) : tut_04.fact(n) ==> factSpec n.toNat := by
  py_begin [tut_04]
  py_loop (inv := fun (r i : Int) => 1 ≤ i ∧ i ≤ n + 1 ∧ r = factSpec (i - 1).toNat)
          (dec := fun (r i : Int) => (n + 1 - i).toNat)
  · obtain rfl : i' = n + 1 := by omega
    simpa using hinv3
  all_goals grind [factSpec, factSpec_step]

set_option warning.simp.varHead false in
/-- `fact(n)` returns `n!` for `n ≥ 0`: any successful run, at any fuel,
yields exactly `.int (factSpec n.toNat)`. A determinism corollary of
`fact_total` — one `py_corollary` (Surface.lean). -/
@[spec] theorem fact_spec (n : Int) (hn : 0 ≤ n) {fuel : Nat} {r : Val}
    (h : callFunction tut_04 "fact" #[.int n] fuel = .ok r) :
    r = .int (factSpec n.toNat) := by
  py_corollary [fact_total]

set_option warning.simp.varHead false in
/-- The typed surface form: binders are `PyInt`, the result is bound
relationally with `⇓`, and neither `Val` nor fuel appears. -/
@[spec] theorem fact_correct (n r : PyInt) (hn : 0 ≤ n) (h : tut_04.fact(n) ⇓ r) :
    r = factSpec n.toNat := by
  py_corollary [fact_total]
