#!/usr/bin/env python3
"""Python -> standardized AST envelope extractor, lean[ block scanner, and
Lean companion-file generator for the lean_models project.

Usage (run from the repo root):

    python3 extractors/python/extract.py <file.py> [more.py ...] [--companion-dir DIR]

For each source file ``foo.py`` this writes:

  * ``foo.json`` next to the source: the envelope described in
    docs/envelope-schema.md (schema v0.1). Sources may live anywhere,
    including per-example directories (``Examples/python/tri/tri.py`` →
    ``Examples/python/tri/tri.json``).
  * ``<companion-dir>/<PascalCaseStem>.lean``: the generated companion file
    described in docs/DESIGN.md (default companion dir: the source file's
    own directory, so ``Examples/python/sum_to/sum_to.py`` →
    ``Examples/python/sum_to/SumTo.lean``) — ONLY when the source contains at
    least one ``# lean[`` block. A pure source (no blocks — the three-file
    per-example layout, where spec.lean and proof.lean are hand-written)
    gets an envelope and nothing else.

Guarantees:
  * Never fails on syntactically valid Python — unknown constructs become
    ``Unsupported`` nodes.
  * Deterministic: same input bytes => same output bytes.
  * Never overwrites a ``.lean`` file that lacks the AUTOGENERATED header
    (a hand-written file at the companion path is a hard error, never
    silently clobbered).
  * The header embeds the source path; a path containing ``/-`` or ``-/``
    would open/close a nested Lean block comment inside the ``/- … -/``
    header and corrupt the companion, so such paths switch the whole header
    to ``--`` line comments (where both sequences are inert). Normal
    repo-relative paths keep the block-comment header byte-for-byte.
  * Hard errors (non-zero exit): unreadable file, syntactically invalid
    Python, invalid stem, unclosed ``# lean[`` block, hand-written file at
    the companion path.

Python 3.9 compatible.
"""

import argparse
import ast
import hashlib
import json
import os
import platform
import re
import sys

SCHEMA_VERSION = "0.1"
FRONTEND = {"name": "cpython-ast", "version": platform.python_version()}

STEM_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
LEAN_OPEN_RE = re.compile(r"^\s*#\s*lean\[\s*$")
LEAN_CLOSE_RE = re.compile(r"^\s*#\s*\]\s*$")
COMMENT_PREFIX_RE = re.compile(r"^\s*#")

ALLOWED_BINOPS = ("Add", "Sub", "Mult", "FloorDiv", "Mod", "Pow")
ALLOWED_UNARYOPS = ("USub", "Not")
ALLOWED_CMPOPS = ("Eq", "NotEq", "Lt", "LtE", "Gt", "GtE",
                  "Is", "IsNot", "In", "NotIn")
# Is/IsNot are emitted structurally for EVERY identity comparison since
# H1-proper: identity is decided dynamically by the interpreter (refs by
# address, None by the singleton test), which loudly refuses the remaining
# out-of-tier operand forms (two non-None immediates — small-int caching,
# str interning are implementation-defined). In/NotIn (membership) are
# likewise structural; the interpreter owns the tier boundary.

UNSUPPORTED_TEXT_LIMIT = 200


class ExtractError(Exception):
    """Fatal extractor error (message is printed to stderr, exit code 1)."""


# ---------------------------------------------------------------------------
# AST -> envelope nodes
# ---------------------------------------------------------------------------

def span(node):
    return {
        "lineno": node.lineno,
        "col_offset": node.col_offset,
        "end_lineno": node.end_lineno,
        "end_col_offset": node.end_col_offset,
    }


def unparse_truncated(node):
    try:
        text = ast.unparse(node)
    except Exception:
        text = ""
    return text[:UNSUPPORTED_TEXT_LIMIT]


def unsupported(node, py_kind=None):
    return {
        "kind": "Unsupported",
        "span": span(node),
        "py_kind": py_kind if py_kind is not None else type(node).__name__,
        "text": unparse_truncated(node),
    }


def literal_const_payload(node):
    """The envelope const payload of a LITERAL expression (an ``ast.Constant``
    of int/bool/str/None — the same encoding as ``Constant`` nodes' ``value``
    field), else None. Note a negative-number default (``lo=-1``) parses as
    ``UnaryOp(USub, Constant)``, NOT a ``Constant`` — non-literal by this
    rule, matching the Lean tier's literals-only defaults decision."""
    if not isinstance(node, ast.Constant):
        return None
    v = node.value
    if v is True or v is False:  # bool before int: bool is an int subtype
        return {"type": "bool", "value": v}
    if isinstance(v, int):
        return {"type": "int", "repr": str(v)}
    if isinstance(v, str):
        return {"type": "str", "value": v}
    if v is None:
        return {"type": "none"}
    return None  # float / bytes / complex / Ellipsis: not a tier literal


def convert_expr(node):
    if isinstance(node, ast.Constant):
        v = node.value
        if v is True or v is False:  # bool before int: bool is an int subtype
            const = {"type": "bool", "value": v}
        elif isinstance(v, int):
            const = {"type": "int", "repr": str(v)}
        elif isinstance(v, str):
            const = {"type": "str", "value": v}
        elif v is None:
            const = {"type": "none"}
        else:  # float / bytes / complex / Ellipsis / ...
            return unsupported(node, "Constant:" + type(v).__name__)
        return {"kind": "Constant", "span": span(node), "value": const}

    if isinstance(node, ast.Name):
        return {"kind": "Name", "span": span(node), "id": node.id}

    if isinstance(node, ast.BinOp):
        op = type(node.op).__name__
        if op not in ALLOWED_BINOPS:
            return unsupported(node, "BinOp:" + op)
        return {
            "kind": "BinOp",
            "span": span(node),
            "left": convert_expr(node.left),
            "op": op,
            "right": convert_expr(node.right),
        }

    if isinstance(node, ast.UnaryOp):
        op = type(node.op).__name__
        if op not in ALLOWED_UNARYOPS:
            return unsupported(node, "UnaryOp:" + op)
        return {
            "kind": "UnaryOp",
            "span": span(node),
            "op": op,
            "operand": convert_expr(node.operand),
        }

    if isinstance(node, ast.BoolOp):
        return {
            "kind": "BoolOp",
            "span": span(node),
            "op": type(node.op).__name__,  # And / Or only
            "values": [convert_expr(v) for v in node.values],
        }

    if isinstance(node, ast.Compare):
        ops = [type(o).__name__ for o in node.ops]
        for op in ops:
            if op not in ALLOWED_CMPOPS:
                return unsupported(node, "Compare:" + op)
        return {
            "kind": "Compare",
            "span": span(node),
            "left": convert_expr(node.left),
            "ops": ops,
            "comparators": [convert_expr(c) for c in node.comparators],
        }

    if isinstance(node, ast.Call):
        reasons = []
        # Plain named keywords are STRUCTURED (H6); `f(**d)` unpacking
        # (a keyword node with arg=None) stays a loud call_unsupported.
        if any(kw.arg is None for kw in node.keywords):
            reasons.append("** unpacking in call")
        if any(isinstance(a, ast.Starred) for a in node.args):
            reasons.append("starred args")
        return {
            "kind": "Call",
            "span": span(node),
            "func": convert_expr(node.func),
            "args": [convert_expr(a) for a in node.args],
            "keywords": [
                {"arg": kw.arg, "value": convert_expr(kw.value)}
                for kw in node.keywords
                if kw.arg is not None
            ],
            "call_unsupported": ", ".join(reasons) if reasons else None,
        }

    if isinstance(node, (ast.List, ast.Tuple)):
        return {
            "kind": type(node).__name__,
            "span": span(node),
            "elts": [convert_expr(e) for e in node.elts],
        }

    if isinstance(node, ast.Dict):
        # `{k: v, ...}` — structured (H0, docs/memory-model.md). A None key
        # is `**expansion`; keep the whole node Unsupported then.
        if any(k is None for k in node.keys):
            return unsupported(node, "Dict:unpack")
        return {
            "kind": "Dict",
            "span": span(node),
            "keys": [convert_expr(k) for k in node.keys],
            "values": [convert_expr(v) for v in node.values],
        }

    if isinstance(node, ast.IfExp):
        # `b if t else o` — structured (H5, sunfish's rotate/value use it)
        return {
            "kind": "IfExp",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": convert_expr(node.body),
            "orelse": convert_expr(node.orelse),
        }

    if isinstance(node, ast.Attribute):
        # `obj.attr` — structured (H0). Store/Del contexts arrive through
        # Assign/Delete targets; representation is context-free here.
        return {
            "kind": "Attribute",
            "span": span(node),
            "value": convert_expr(node.value),
            "attr": node.attr,
        }

    if isinstance(node, ast.Subscript):
        # CPython >= 3.9: `slice` is the index expr itself when it is a plain
        # expression; a Slice node is structured (H5 strings — sunfish's
        # `board[::-1]` / `board[:i]`); pre-3.9 ExtSlice/Index => whole node
        # Unsupported.
        sl = node.slice
        sl_kind = type(sl).__name__
        if sl_kind == "Slice":
            d = {
                "kind": "Slice",
                "span": span(node),
                "value": convert_expr(node.value),
            }
            # Components are emitted only when present in the source —
            # envelopes mirror CPython's ast (ingestion fills the absent
            # ones with `Constant None`, CPython's own BUILD_SLICE value).
            if sl.lower is not None:
                d["lower"] = convert_expr(sl.lower)
            if sl.upper is not None:
                d["upper"] = convert_expr(sl.upper)
            if sl.step is not None:
                d["step"] = convert_expr(sl.step)
            return d
        if sl_kind in ("ExtSlice", "Index"):
            return unsupported(node, "Subscript:" + sl_kind)
        return {
            "kind": "Subscript",
            "span": span(node),
            "value": convert_expr(node.value),
            "index": convert_expr(sl),
        }

    if isinstance(node, ast.GeneratorExp):
        # H4: a generator EXPRESSION is structured only in the v0 shape --
        # ONE `for` clause, not `async`. CPython compiles every genexp into
        # an implicit generator FUNCTION whose first argument is the
        # already-evaluated outer iterator, and ingestion performs exactly
        # that lowering; a multi-clause genexp is that lowering applied
        # twice, which v0 does not do, so it stays Unsupported (loud) rather
        # than half-structured. `ifs` are the clause's filters, in order.
        gens = node.generators
        if len(gens) == 1 and not getattr(gens[0], "is_async", 0):
            g = gens[0]
            return {
                "kind": "GeneratorExp",
                "span": span(node),
                "elt": convert_expr(node.elt),
                "target": convert_expr(g.target),
                "iter": convert_expr(g.iter),
                "ifs": [convert_expr(i) for i in g.ifs],
            }
        return unsupported(node, "GeneratorExp")

    return unsupported(node)


def convert_param(p, default=None):
    """Schema ``param``. ``default`` (a const payload) is emitted only when
    present, so envelopes of default-free sources are byte-identical to the
    pre-defaults format."""
    d = {"arg": p.arg, "span": span(p)}
    if default is not None:
        d["default"] = default
    return d


def _walk_scope(fn):
    """All nodes of fn's own scope: descends the body but not into nested
    scopes (defs/lambdas/classes — Unsupported nodes in v0 anyway)."""
    stack = list(ast.iter_child_nodes(fn))
    while stack:
        node = stack.pop()
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda,
                             ast.ClassDef)):
            continue
        yield node
        stack.extend(ast.iter_child_nodes(node))


def _target_bound_names(t):
    """Names an assignment TARGET binds, per CPython's scoping rules: bare
    names bind; tuple/list/starred targets recurse; subscript/attribute
    targets bind NOTHING (``tp[k(x)] = v`` makes neither ``tp`` nor ``k``
    local — walking the whole target tree used to overapproximate here and
    falsely shadowed callees appearing inside subscript keys)."""
    if isinstance(t, ast.Name):
        return [t.id]
    if isinstance(t, (ast.Tuple, ast.List)):
        return [n for e in t.elts for n in _target_bound_names(e)]
    if isinstance(t, ast.Starred):
        return _target_bound_names(t.value)
    return []  # Subscript / Attribute: no binding


def _assigned_names(fn):
    """Names the function body assigns (CPython's static-locals rule makes
    these local THROUGHOUT the body). Params excluded."""
    names = set()
    for node in _walk_scope(fn):
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, (ast.AugAssign, ast.AnnAssign, ast.For)):
            targets = [node.target]
        else:
            continue
        for t in targets:
            names.update(_target_bound_names(t))
    return names


def _shadowed_calls(fn):
    """Called names that the body also assigns: CPython would treat the callee
    as an (initially unbound) local, so a dynamic-env interpreter cannot be
    faithful. Emitted as `locals_unsupported` so the interpreter refuses
    loudly.

    H7 refinement (the closure-escape pattern `g = _mk(a); g()`): a name
    bound EXACTLY ONCE, by a single-target plain assignment DIRECTLY in the
    body (so never inside a loop), with every call textually AFTER it, has
    no UnboundLocalError window — the dynamic env is faithful there, so it
    is not flagged."""
    assigned = _assigned_names(fn)
    hits = set()
    for node in _walk_scope(fn):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in assigned:
                hits.add(node.func.id)
    safe = set()
    for name in hits:
        linenos = _binding_linenos(fn, name)
        direct_assigns = [
            st for st in fn.body
            if isinstance(st, ast.Assign) and len(st.targets) == 1
            and isinstance(st.targets[0], ast.Name)
            and st.targets[0].id == name
        ]
        if len(linenos) == 1 and len(direct_assigns) == 1:
            ln = direct_assigns[0].lineno
            calls = [n.lineno for n in _walk_scope(fn)
                     if isinstance(n, ast.Call)
                     and isinstance(n.func, ast.Name) and n.func.id == name]
            if all(c > ln for c in calls):
                safe.add(name)
    return sorted(hits - safe)


def _has_global(node):
    """Does the whole subtree (nested scopes INCLUDED — a nested def's
    ``global`` also rebinds module names when called) contain a ``global``
    statement? Emitted on FunctionDef/ClassDef as ``"has_global": true``
    (key absent when false, keeping global-free envelopes byte-identical).
    Consumed by ingestion's namedtuple binding census: with this exact
    fact, opaque function-body statements (``try``/``with``/…) need no
    conservative refusal."""
    return any(isinstance(n, ast.Global) for n in ast.walk(node))


def _is_generator(fn):
    """Is this ``def`` a GENERATOR function? CPython's rule is purely
    syntactic and scope-local: a ``def`` whose OWN scope contains a ``yield``
    or ``yield from`` compiles to a generator, whether or not that yield is
    reachable -- calling it never runs the body, it builds a generator
    object. Unlike ``_has_global`` this must NOT descend into nested scopes:
    a nested ``def``'s yield makes the NESTED function a generator, not this
    one (``_walk_scope`` already stops at def/lambda/class boundaries)."""
    return any(isinstance(n, (ast.Yield, ast.YieldFrom)) for n in _walk_scope(fn))


def _binding_linenos(fn, name):
    """Line numbers of every statement in fn's OWN scope that BINDS `name`
    (assignment, augmented assignment, annotated assignment, `for` target,
    `del`, imports, `with … as`). Used by the H7 never-rebound-after-def
    analysis — `del` and imports count as bindings on purpose."""
    out = []
    for n in _walk_scope(fn):
        bound = []
        if isinstance(n, ast.Assign):
            for t in n.targets:
                bound += _target_bound_names(t)
        elif isinstance(n, (ast.AugAssign, ast.AnnAssign, ast.For)):
            bound += _target_bound_names(n.target)
        elif isinstance(n, ast.Delete):
            for t in n.targets:
                bound += _target_bound_names(t)
        elif isinstance(n, (ast.Import, ast.ImportFrom)):
            for al in n.names:
                bound.append((al.asname or al.name).split(".")[0])
        elif isinstance(n, ast.With):
            for item in n.items:
                if item.optional_vars is not None:
                    bound += _target_bound_names(item.optional_vars)
        if name in bound:
            out.append(n.lineno)
    return out


def _closure_analysis(nd, enclosing):
    """H7 nested defs (docs/memory-model.md §nested defs and closures):
    the capture set and the LOUD refusals of the snapshot tier.

    Captures = free names of the nested body (own scope) that are locals
    or parameters of the enclosing function — CPython's symtable rule.
    Snapshot-at-def equals CPython's cells exactly when no captured name
    is bound after the def executes; the analysis refuses (with the
    precise reason) everything outside that fragment. Returns
    ``(captures, reason_or_None)``."""
    reasons = []
    for n in ast.walk(nd):
        if n is not nd and isinstance(
                n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda,
                    ast.ClassDef)):
            reasons.append("a scope nested inside the nested def")
            break
    if any(isinstance(n, ast.Nonlocal) for n in ast.walk(nd)):
        reasons.append("nonlocal (cell writes)")
    nested_locals = ({p.arg for p in list(nd.args.posonlyargs) + list(nd.args.args)}
                     | _assigned_names(nd))
    enclosing_params = {p.arg for p in list(enclosing.args.posonlyargs)
                        + list(enclosing.args.args)}
    # direct nested-def names are enclosing locals too (a closure may
    # capture an earlier closure — sunfish-adjacent `chain` shapes)
    def_bindings = {st.name: st.lineno for st in enclosing.body
                    if isinstance(st, ast.FunctionDef)}
    enclosing_locals = (enclosing_params | _assigned_names(enclosing)
                        | set(def_bindings))
    free = set()
    for n in _walk_scope(nd):
        if isinstance(n, ast.Name) and n.id not in nested_locals:
            free.add(n.id)
    captures = sorted(free & enclosing_locals)
    for c in captures:
        linenos = _binding_linenos(enclosing, c)
        if c in def_bindings:
            linenos = linenos + [def_bindings[c]]
        after = [ln for ln in linenos if ln > nd.lineno]
        if after:
            reasons.append(
                "captured name %r is rebound after the def (line %d) — "
                "snapshot-at-def would diverge from CPython's cell"
                % (c, min(after)))
        elif c not in enclosing_params and not [ln for ln in linenos
                                                if ln < nd.lineno]:
            reasons.append(
                "captured name %r has no binding before the def — the "
                "snapshot could miss CPython's late cell fill" % c)
    return captures, ("; ".join(reasons) if reasons else None)


def _early_nested_calls(fn):
    """Calls of a DIRECT nested-def name at a line before its def: CPython's
    static-locals rule makes the name local throughout, so such a call
    raises UnboundLocalError — a dynamic-env fallthrough to a module name
    would be silently wrong. Loud, via `locals_unsupported`."""
    defs = {st.name: st.lineno for st in fn.body
            if isinstance(st, ast.FunctionDef)}
    hits = set()
    for n in _walk_scope(fn):
        if (isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
                and n.func.id in defs and n.lineno < defs[n.func.id]):
            hits.add(n.func.id)
    return sorted(hits)


def convert_stmt(node, enclosing=None):
    if isinstance(node, ast.FunctionDef):
        a = node.args
        plain = list(a.posonlyargs) + list(a.args)
        reasons = []
        # Positional defaults: LITERAL defaults (int/bool/str/None Constant)
        # are in-tier — emitted as a "default" const payload on the trailing
        # params (a.defaults aligns with the tail of posonly+args, per
        # CPython). Any NON-literal default (a Name like easter's
        # EASTER_WESTERN, a negative number, a call, a mutable [] / {}) keeps
        # the whole function at args_unsupported: "defaults" with no
        # "default" keys emitted — refused loudly at call time, as before.
        payloads = [literal_const_payload(d) for d in a.defaults]
        if a.defaults and not all(p is not None for p in payloads):
            reasons.append("defaults")
            payloads = []
        first_defaulted = len(plain) - len(payloads)
        params = [
            convert_param(p, payloads[i - first_defaulted]
                          if i >= first_defaulted else None)
            for i, p in enumerate(plain)
        ]
        if a.vararg is not None:
            reasons.append("*args")
        if a.kwonlyargs:
            reasons.append("keyword-only args")
        if a.kwarg is not None:
            reasons.append("**kwargs")
        if node.decorator_list:
            reasons.append("decorators")
        out = {
            "kind": "FunctionDef",
            "span": span(node),
            "name": node.name,
            "args": params,
            "args_unsupported": ", ".join(reasons) if reasons else None,
            "locals_unsupported": (
                "calls locally-assigned name(s) (static-locals rule): "
                + ", ".join(shadowed)
                if (shadowed := _shadowed_calls(node))
                else (
                    "calls nested-def name(s) before the def (static-locals "
                    "rule): " + ", ".join(early)
                    if (early := _early_nested_calls(node))
                    else None
                )
            ),
            # a nested def DIRECTLY in this body is the H7 closure shape;
            # one nested deeper (inside an if/loop) stays a plain
            # FunctionDef node, which ingestion refuses loudly
            "body": [convert_stmt(s, enclosing=node) for s in node.body],
        }
        if _has_global(node):
            out["has_global"] = True
        if _is_generator(node):
            out["is_generator"] = True
        if enclosing is not None:
            # H7 (docs/memory-model.md §nested defs and closures): a def
            # DIRECTLY inside a function body is structured as NestedDef,
            # with the capture set and the snapshot tier's refusals
            captures, refusal = _closure_analysis(node, enclosing)
            out["kind"] = "NestedDef"
            out["captures"] = captures
            out["closure_unsupported"] = refusal
        return out

    if isinstance(node, ast.ClassDef):
        # Structured (H3, docs/memory-model.md). The interpreter owns the
        # tier boundary, but features that change what a DEFINITION means
        # (bases/metaclass/decorators, class-level statements binding class
        # attributes) are flagged here, like args_unsupported: the class is
        # represented, instantiation refuses loudly.
        reasons = []
        namedtuple_base = None
        if node.bases:
            # A SINGLE base that is a plain `namedtuple(...)` call is the
            # recorded value-like subclass shape (sunfish's Position):
            # emitted structurally as `namedtuple_base` (ingestion
            # validates the spec and the module census; on any failure the
            # class demotes to the ordinary uninstantiable-loudly state).
            # Any other base keeps the loud inheritance reason.
            b = node.bases[0]
            if (len(node.bases) == 1 and isinstance(b, ast.Call)
                    and isinstance(b.func, ast.Name)
                    and b.func.id == "namedtuple" and not b.keywords):
                namedtuple_base = convert_expr(b)
            else:
                reasons.append("bases (inheritance)")
        if node.keywords:
            reasons.append("class keywords (metaclass)")
        if node.decorator_list:
            reasons.append("decorators")
        for s in node.body:
            if isinstance(s, ast.FunctionDef):
                continue
            if isinstance(s, ast.Pass):
                continue
            if isinstance(s, ast.Expr) and isinstance(s.value, ast.Constant):
                continue  # docstring / stray constant
            reasons.append("class-level statements (class attributes)")
            break
        out = {
            "kind": "ClassDef",
            "span": span(node),
            "name": node.name,
            "class_unsupported": ", ".join(reasons) if reasons else None,
            "body": [convert_stmt(s) for s in node.body],
        }
        if namedtuple_base is not None:
            out["namedtuple_base"] = namedtuple_base
        if _has_global(node):
            out["has_global"] = True
        return out

    if isinstance(node, ast.Return):
        return {
            "kind": "Return",
            "span": span(node),
            "value": convert_expr(node.value) if node.value is not None else None,
        }

    if isinstance(node, ast.Assign):
        return {
            "kind": "Assign",
            "span": span(node),
            "targets": [convert_expr(t) for t in node.targets],
            "value": convert_expr(node.value),
        }

    if isinstance(node, ast.AugAssign):
        op = type(node.op).__name__
        if op not in ALLOWED_BINOPS:
            return unsupported(node, "AugAssign:" + op)
        return {
            "kind": "AugAssign",
            "span": span(node),
            "target": convert_expr(node.target),
            "op": op,
            "value": convert_expr(node.value),
        }

    if isinstance(node, ast.While):
        return {
            "kind": "While",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": [convert_stmt(s) for s in node.body],
            "orelse": [convert_stmt(s) for s in node.orelse],
        }

    if isinstance(node, ast.For):
        # Plain `for` only; `async for` is a different node class
        # (ast.AsyncFor) and falls through to Unsupported.
        return {
            "kind": "For",
            "span": span(node),
            "target": convert_expr(node.target),
            "iter": convert_expr(node.iter),
            "body": [convert_stmt(s) for s in node.body],
            "orelse": [convert_stmt(s) for s in node.orelse],
        }

    if isinstance(node, ast.If):
        return {
            "kind": "If",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": [convert_stmt(s) for s in node.body],
            "orelse": [convert_stmt(s) for s in node.orelse],
        }

    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Yield):
        # H4: `yield e` in STATEMENT position -- the only yield the tier
        # admits (a yield in EXPRESSION position receives a `send` value and
        # stays loudly out, so it keeps falling through to Unsupported).
        # A bare `yield` emits no "value" key; ingestion fills `Constant
        # None`, CPython's own compilation -- the `Slice` convention.
        d = {"kind": "Yield", "span": span(node)}
        if node.value.value is not None:
            d["value"] = convert_expr(node.value.value)
        return d

    if isinstance(node, ast.Expr):
        return {"kind": "Expr", "span": span(node), "value": convert_expr(node.value)}

    if isinstance(node, ast.Pass):
        return {"kind": "Pass", "span": span(node)}
    if isinstance(node, ast.Break):
        return {"kind": "Break", "span": span(node)}
    if isinstance(node, ast.Continue):
        return {"kind": "Continue", "span": span(node)}

    return unsupported(node)


# ---------------------------------------------------------------------------
# lean[ block scanner
# ---------------------------------------------------------------------------

def strip_comment_marker(line):
    """Strip the leading ^\\s*# and at most one following space.

    Lines inside a block that do not carry a comment marker (e.g. blank lines)
    are kept verbatim.
    """
    m = COMMENT_PREFIX_RE.match(line)
    if m is None:
        return line
    rest = line[m.end():]
    if rest.startswith(" "):
        rest = rest[1:]
    return rest


def scan_lean_blocks(lines, path):
    """Return [{"first_line": ..., "last_line": ..., "text": ...}, ...].

    first_line/last_line are the 1-based line numbers of the `# lean[` and
    `# ]` marker lines. text is the joined inner lines, comment markers
    stripped, no trailing newline. Unclosed block => ExtractError.
    """
    blocks = []
    i = 0
    n = len(lines)
    while i < n:
        if LEAN_OPEN_RE.match(lines[i]):
            first_line = i + 1
            j = i + 1
            inner = []
            while j < n and not LEAN_CLOSE_RE.match(lines[j]):
                inner.append(strip_comment_marker(lines[j]))
                j += 1
            if j >= n:
                raise ExtractError(
                    "%s:%d: unclosed '# lean[' block (no matching '# ]')"
                    % (path, first_line)
                )
            blocks.append(
                {"first_line": first_line, "last_line": j + 1, "text": "\n".join(inner)}
            )
            i = j + 1
        else:
            i += 1
    return blocks


# ---------------------------------------------------------------------------
# Companion generation
# ---------------------------------------------------------------------------

def pascal_case(stem):
    """my_func -> MyFunc (split on '_', uppercase first letter of each part)."""
    return "".join(p[:1].upper() + p[1:] for p in stem.split("_"))


AUTOGEN_MARKER = "AUTOGENERATED by extractors/python/extract.py"


def header_lines(source_rel, source_sha256):
    """The companion's AUTOGENERATED header.

    Default form: a Lean block comment (kept byte-identical to the historical
    format so unchanged sources regenerate byte-stably). But the source path
    is embedded verbatim, and inside ``/- … -/`` a path containing ``/-``
    opens a *nested* block comment (resp. ``-/`` closes the header early) —
    the companion then dies with "unterminated comment" at EOF. Such paths
    (e.g. scratch roots with dash-leading segments) switch the whole header
    to ``--`` line comments, where both sequences are inert.
    """
    if "/-" in source_rel or "-/" in source_rel:
        return [
            "-- " + AUTOGEN_MARKER + " — DO NOT EDIT.",
            "-- source: " + source_rel,
            "-- sha256: " + source_sha256,
        ]
    return [
        "/-",
        AUTOGEN_MARKER + " — DO NOT EDIT.",
        "source: " + source_rel,
        "sha256: " + source_sha256,
        "-/",
    ]


def check_companion_overwritable(companion_path):
    """Hard error unless companion_path is absent or extractor-generated
    (AUTOGENERATED marker within its first three lines — where both header
    forms carry it). Never silently clobber a hand-written .lean file."""
    if not os.path.exists(companion_path):
        return
    try:
        with open(companion_path, "r", encoding="utf-8", errors="replace") as f:
            head = f.read(512)
    except OSError as e:
        raise ExtractError("%s: cannot read existing companion: %s"
                           % (companion_path, e))
    if not any(AUTOGEN_MARKER in ln for ln in head.split("\n")[:3]):
        raise ExtractError(
            "%s: refusing to overwrite — the existing file lacks the "
            "AUTOGENERATED header (hand-written?). Move it aside or pass a "
            "different --companion-dir." % companion_path
        )


def generate_companion(stem, source_rel, json_rel, source_sha256, blocks):
    hoisted = []  # deduped, order-preserving across all blocks
    block_bodies = []
    for b in blocks:
        body_lines = []
        for ln in b["text"].split("\n") if b["text"] != "" else []:
            if ln.startswith("import "):
                if ln not in hoisted:
                    hoisted.append(ln)
            else:
                body_lines.append(ln)
        block_bodies.append("\n".join(body_lines))

    parts = header_lines(source_rel, source_sha256) + [
        "import LeanModels",
    ]
    parts.extend(hoisted)
    parts.append("")
    parts.append("open LeanModels LeanModels.Python")
    parts.append("")
    parts.append('load_program %s from "%s"' % (stem, json_rel))
    for body in block_bodies:
        if body.strip() == "":
            continue  # block contained only imports (or nothing)
        parts.append("")
        parts.append(body)
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def rel_posix(path):
    """Normalize a user-supplied path for use inside emitted files."""
    return os.path.normpath(path).replace(os.sep, "/")


def process_file(source_path, companion_dir):
    stem = os.path.splitext(os.path.basename(source_path))[0]
    if not STEM_RE.match(stem):
        raise ExtractError(
            "%s: stem %r is not a valid identifier (must match ^[A-Za-z_][A-Za-z0-9_]*$)"
            % (source_path, stem)
        )

    try:
        with open(source_path, "rb") as f:
            data = f.read()
    except OSError as e:
        raise ExtractError("%s: cannot read: %s" % (source_path, e))

    source_sha256 = hashlib.sha256(data).hexdigest()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as e:
        raise ExtractError("%s: not valid UTF-8: %s" % (source_path, e))

    try:
        tree = ast.parse(text, filename=source_path)
    except SyntaxError as e:
        raise ExtractError("%s: syntax error: %s" % (source_path, e))

    blocks = scan_lean_blocks(text.splitlines(), source_path)

    source_rel = rel_posix(source_path)
    json_rel = os.path.splitext(source_rel)[0] + ".json"

    envelope = {
        "schema_version": SCHEMA_VERSION,
        "language": "python",
        "frontend": {"name": FRONTEND["name"], "version": FRONTEND["version"]},
        "source_file": source_rel,
        "source_sha256": source_sha256,
        "module": {"kind": "Module", "body": [convert_stmt(s) for s in tree.body]},
        "lean_blocks": blocks,
    }

    json_path = os.path.splitext(source_path)[0] + ".json"
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(envelope, f, indent=2)
        f.write("\n")

    if not blocks:
        # Pure source (three-file per-example layout): envelope only. The
        # spec/proof .lean files are hand-written siblings, never generated.
        return

    if companion_dir is None:
        # Default: the companion lives next to its source (per-example
        # directory layout — Examples/python/sum_to/sum_to.py → Examples/python/sum_to/).
        companion_dir = os.path.dirname(source_path) or "."
    companion_path = os.path.join(companion_dir, pascal_case(stem) + ".lean")
    check_companion_overwritable(companion_path)
    companion_text = generate_companion(stem, source_rel, json_rel, source_sha256, blocks)
    os.makedirs(companion_dir, exist_ok=True)
    with open(companion_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(companion_text)


def main(argv=None):
    sys.setrecursionlimit(10000)
    parser = argparse.ArgumentParser(
        prog="extract.py",
        description="Extract Python sources to envelope JSON + Lean companion files "
        "(run from the repo root).",
    )
    parser.add_argument("sources", nargs="+", metavar="file.py")
    parser.add_argument(
        "--companion-dir",
        default=None,
        help="directory for generated companion .lean files "
        "(default: the source file's own directory)",
    )
    args = parser.parse_args(argv)

    try:
        for src in args.sources:
            process_file(src, args.companion_dir)
    except ExtractError as e:
        print("error: %s" % e, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
