#!/usr/bin/env python3
"""Python -> standardized AST envelope extractor, lean[ block scanner, and
Lean companion-file generator for the lean_models project.

Usage (run from the repo root):

    python3 extractors/python/extract.py <file.py> [more.py ...] [--companion-dir DIR]
    python3 extractors/python/extract.py <file.py> --out DIR_OR_FILE.json

For each source file ``foo.py`` this writes:

  * ``foo.json`` next to the source: the envelope described in
    docs/envelope-schema.md (schema v0.1). Sources may live anywhere,
    including per-example directories (``Examples/python/tri/tri.py`` →
    ``Examples/python/tri/tri.json``).
  * ``<companion-dir>/<PascalCaseStem>.lean``: the generated companion file
    described in docs/DESIGN.md (default companion dir: the source file's
    own directory, so ``Examples/python/sum_to/sum_to.py`` →
    ``Examples/python/sum_to/SumTo.lean``) — ONLY when the source contains at
    least one ``# lean[`` block. A pure source (no blocks — the three-file
    per-example layout, where spec.lean and proof.lean are hand-written)
    gets an envelope and nothing else.

``--out`` redirects the envelope (a directory, or an explicit ``.json``
path) instead of writing it next to the source — how ``tools/leanpy``
ingests ARBITRARY files it must not write into (a read-only tree, someone
else's project, the vendored CPython corpus). ``source_file`` still records
the real source path. A stem that is not a Python identifier is then
allowed too (the identifier rule exists for the generated companion's
name); a source with ``# lean[`` blocks still needs a valid stem, since a
companion is still generated.

Guarantees:
  * Never fails on syntactically valid Python — unknown constructs become
    ``Unsupported`` nodes.
  * Deterministic: same input bytes => same output bytes.
  * Never overwrites a ``.lean`` file that lacks the AUTOGENERATED header
    (a hand-written file at the companion path is a hard error, never
    silently clobbered).
  * The header embeds the source path; a path containing ``/-`` or ``-/``
    would open/close a nested Lean block comment inside the ``/- … -/``
    header and corrupt the companion, so such paths switch the whole header
    to ``--`` line comments (where both sequences are inert). Normal
    repo-relative paths keep the block-comment header byte-for-byte.
  * Hard errors (non-zero exit): unreadable file, syntactically invalid
    Python, invalid stem, unclosed ``# lean[`` block, hand-written file at
    the companion path.

Python 3.9 compatible.
"""

import argparse
import ast
import hashlib
import json
import os
import platform
import re
import sys

SCHEMA_VERSION = "0.1"
FRONTEND = {"name": "cpython-ast", "version": platform.python_version()}

STEM_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
LEAN_OPEN_RE = re.compile(r"^\s*#\s*lean\[\s*$")
LEAN_CLOSE_RE = re.compile(r"^\s*#\s*\]\s*$")
COMMENT_PREFIX_RE = re.compile(r"^\s*#")

ALLOWED_BINOPS = ("Add", "Sub", "Mult", "FloorDiv", "Mod", "Pow",
                  # pass 5 (docs/memory-model.md "Left shift and bitwise
                  # or"): `1 << 63` and `live |= ...` in the post-#158
                  # shipped file; the interpreter owns the value tier
                  # (negative `|` operands compute exactly there since
                  # the tail batch admitted `&` — docs/memory-model.md
                  # §bitwise `&`).
                  "LShift", "BitOr", "BitAnd")
ALLOWED_UNARYOPS = ("USub", "Not")
ALLOWED_CMPOPS = ("Eq", "NotEq", "Lt", "LtE", "Gt", "GtE",
                  "Is", "IsNot", "In", "NotIn")
# Is/IsNot are emitted structurally for EVERY identity comparison since
# H1-proper: identity is decided dynamically by the interpreter (refs by
# address, None by the singleton test), which loudly refuses the remaining
# out-of-tier operand forms (two non-None immediates — small-int caching,
# str interning are implementation-defined). In/NotIn (membership) are
# likewise structural; the interpreter owns the tier boundary.

UNSUPPORTED_TEXT_LIMIT = 200

# A LOWERING THAT SYNTHESIZES A NAME OWES A CENSUS — the rule the starred
# lane's implementation extracted, and there are now two lowerings paying
# it. Each spells source that performs NO name lookup as a call of a name
# the source never wrote, and the interpreter reaches its builtins only
# AFTER every shadow-resolving arm; so a module that binds the name would
# run the lowering through the shadow and be SILENTLY WRONG. One census,
# one flag per lowering, and the name set carries the reason.
_MODULE_BINDS_STR = False           # f-strings: `{x}` lowers to `str(x)`
_MODULE_SHADOWS_DISPLAY = False     # starred displays: `[*a]` -> `list(tuple(a))`

FSTRING_LOWERING_NAMES = ("str",)
DISPLAY_LOWERING_NAMES = ("list", "tuple")


def binds_any_name(tree, names):
    """Does the module bind any of ``names`` ANYWHERE — any scope, any
    binding form? Conservative and whole-module by design: the alternative
    to over-refusing here is being silently wrong. (Until 2026-08-16 this
    existed twice — `binds_str` was this function with `names = {"str"}`
    inlined, which is exactly the duplicate a second lowering exposes.)"""
    for n in ast.walk(tree):
        if isinstance(n, ast.Name) and isinstance(n.ctx, (ast.Store, ast.Del)):
            if n.id in names:
                return True
        elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if n.name in names:
                return True
        elif isinstance(n, ast.arg):
            if n.arg in names:
                return True
        elif isinstance(n, ast.alias):
            if (n.asname or n.name.split(".")[0]) in names:
                return True
        elif isinstance(n, ast.ExceptHandler):
            if n.name in names:
                return True
        elif isinstance(n, (ast.Global, ast.Nonlocal)):
            if any(x in names for x in n.names):
                return True
    return False


# Pass 0 import forms (docs/memory-model.md paragraph "Import forms
# (Pass 0)"): the two ImportFrom rows of the exact-text benign-import
# whitelist (`benignImportBinds`, Ast.lean; `BENIGN_IMPORTS`,
# harness/leanpy_survey.py -- keep all three in sync). These rows are
# STRUCTURED here like every other admitted from-import and rewritten
# back to the legacy Unsupported node at ingestion (Json.lean, the one
# rewrite site), so the five text-keyed whitelist consumers see today's
# shape unchanged. `import time` is a plain Import and never reaches
# the ImportFrom arm.
BENIGN_IMPORT_FROM = frozenset((
    "from itertools import count",
    "from collections import namedtuple",
))

# THE §2.5 ACCELERATOR-EQUIVALENCE REGISTRY (2026-08-16; docs/memory-model.md
# §import forms -- "per-module differential admission").
#
# A guarded `from <C module> import ...` of a module the pinned platform
# SHIPS is the one import form where CPython succeeds and the model does
# not: the model's Pass 0 raises, the guard catches it, and the PURE
# FALLBACK runs where CPython ran C. Admitting that continuation ASSERTS
# observational equivalence of the two branches, and the memo's own words
# (docs/c-intrinsics-proposal.md 2.5) are that the assertion "is not taken
# from the docs: every such file gets differential battery rows ... and any
# divergence -- a message, a type, an edge case -- is a blocker, not a
# footnote."
#
# Until 2026-08-16 the admission was granted to EVERY platform-present
# module in guard position. Measured over the library corpus that is 24
# distinct accelerators in ~30 files, of which exactly ONE had ever been
# differentially tested. Library mode then tested a second one and it
# FAILED (`stat`, 21 of 104 calls). An assertion made 24 times and checked
# once is not an assertion, so the admission is a REGISTRY: an accelerator
# is admitted only with a recorded measurement that PASSED, and its
# evidence is cited here. NO ENTRY MEANS NO ADMISSION -- the refusal is
# loud and named (`ImportFrom:accelerator-unmeasured`), never a silent
# fallback run. A measured-FALSE entry refuses under its own name
# (`ImportFrom:accelerator-diverges`), so the census can tell "nobody
# looked" from "we looked and it is wrong".
#
# To ADD an entry: drive the module's public surface through
# `harness/library_survey.py` (the CALLS phase IS this instrument -- it
# runs the model's fallback against CPython's C accelerator), record the
# numerator and denominator, and cite the run.
ACCELERATOR_ADMISSIONS = {
    "_bisect": {
        "equivalent": True,
        "fallback": "bisect.py (`from _bisect import *`, 3.9.19 lines 73-76)",
        "evidence": "library mode 2026-08-16 (docs/backlog.md 'THE BASELINE "
                    "SCOREBOARD'): 15 of 15 comparable battery calls agree, 0 "
                    "diverge, against the real `_bisect`. The remainder of the "
                    "battery is loud refusals (`<` across mixed types; the "
                    "designed, unbuilt `list.insert`), never silent agreement.",
    },
    "_stat": {
        "equivalent": False,
        "fallback": "stat.py (`from _stat import *`, 3.9.19 lines 192-195)",
        "evidence": "library mode 2026-08-16: 21 of 104 battery calls DIVERGE. "
                    "C `_stat` converts its argument to an unsigned int, so "
                    "`S_IFMT(-1)` raises OverflowError and `S_ISDOOR('a')` "
                    "raises TypeError, where the pure fallback answers 61440 "
                    "and False (`S_ISDOOR`/`S_ISPORT`/`S_ISWHT` are literally "
                    "`return False` in 3.9 and accept anything). The MODEL is "
                    "faithful to the file; the equivalence claim is what is "
                    "false, on the negative-int and non-int domains.",
    },
    "_opcode": {
        "equivalent": False,
        "fallback": "opcode.py (`from _opcode import stack_effect` + "
                    "`__all__.append('stack_effect')`, 3.9.19 lines 18-21)",
        "evidence": "NO BATTERY NEEDED -- the two branches differ in the NAMES "
                    "they bind, which is inspection, not measurement. CPython "
                    "binds `stack_effect` and appends it to `__all__`; the "
                    "fallback (`pass`) binds neither. docs/memory-model.md "
                    "already called this 'the recorded 2.5 divergence, unseen "
                    "because __all__ is never printed' -- and 'unseen' is not "
                    "'equivalent'. Cost, stated: opcode.py's program-mode MATCH "
                    "(the `%` landing's flip) is WITHDRAWN. It was a match on "
                    "empty stdout over a module namespace that differs, and the "
                    "module system (L2) is exactly what makes that namespace "
                    "observable. One line of this registry reverses it if the "
                    "owner would rather keep the flip.",
    },
}

_PLATFORM_INVENTORY = None


def platform_inventory():
    """The PINNED PLATFORM INVENTORY: top-level module names the pinned
    interpreter ships (committed data, captured by subprocess -- see
    capture_inventory.py; the census C-table / `isPyBuiltinName`
    discipline: no absence is ever guessed). Loaded lazily -- only an
    unguarded, non-benign from-import of admissible shape needs it --
    and a missing/corrupt file is a hard ExtractError, never a silent
    empty set (an empty set would admit EVERY module as absent and
    surface wrong ImportErrors)."""
    global _PLATFORM_INVENTORY
    if _PLATFORM_INVENTORY is None:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "platform_inventory.json")
        try:
            with open(path, "r", encoding="utf-8") as f:
                modules = json.load(f)["modules"]
        except (OSError, ValueError, KeyError) as e:
            raise ExtractError(
                "platform_inventory.json is missing or unreadable (%s); "
                "the absent-module import admission cannot be decided "
                "without it -- regenerate with capture_inventory.py "
                "against the pinned CPython 3.9.19" % (e,))
        _PLATFORM_INVENTORY = frozenset(modules)
    return _PLATFORM_INVENTORY


class ExtractError(Exception):
    """Fatal extractor error (message is printed to stderr, exit code 1)."""


# ---------------------------------------------------------------------------
# AST -> envelope nodes
# ---------------------------------------------------------------------------

def span(node):
    return {
        "lineno": node.lineno,
        "col_offset": node.col_offset,
        "end_lineno": node.end_lineno,
        "end_col_offset": node.end_col_offset,
    }


def unparse_truncated(node):
    try:
        text = ast.unparse(node)
    except Exception:
        text = ""
    return text[:UNSUPPORTED_TEXT_LIMIT]


def unsupported(node, py_kind=None):
    return {
        "kind": "Unsupported",
        "span": span(node),
        "py_kind": py_kind if py_kind is not None else type(node).__name__,
        "text": unparse_truncated(node),
    }


def literal_const_payload(node):
    """The envelope const payload of a LITERAL expression (an ``ast.Constant``
    of int/bool/str/None — the same encoding as ``Constant`` nodes' ``value``
    field), else None. Note a negative-number default (``lo=-1``) parses as
    ``UnaryOp(USub, Constant)``, NOT a ``Constant`` — non-literal by this
    rule, matching the Lean tier's literals-only defaults decision."""
    if not isinstance(node, ast.Constant):
        return None
    v = node.value
    if v is True or v is False:  # bool before int: bool is an int subtype
        return {"type": "bool", "value": v}
    if isinstance(v, int):
        return {"type": "int", "repr": str(v)}
    if isinstance(v, str):
        return {"type": "str", "value": v}
    if v is None:
        return {"type": "none"}
    return None  # float / bytes / complex / Ellipsis: not a tier literal


def convert_fstring(node):
    """Lower an f-string to `"a" + str(x) + "b"` (docs/memory-model.md
    §f-strings): literal text becomes a str `Constant`, each field becomes a
    `str(…)` `Call`, and the pieces join left-associatively with `BinOp Add`
    — CPython's `{x}` IS `format(x, '')`, which equals `str(x)` for every
    value in this tier. Zero new node kinds, so nothing downstream moves.

    The tier line falls out of that equality: a non-empty FORMAT SPEC is
    where `format(v, spec)` and `str(v)` diverge (a whole mini-language —
    a parallel table this development refuses), and `!r`/`!a` name
    operations that are not tier callables. Each is refused LOUDLY on the
    whole node, never half-lowered. `{x=}` needs no arm of its own: CPython
    3.8+ compiles it to the text `x=` plus a `!r` field, which is itself
    the evidence that the AST does not carry the source text."""
    if _MODULE_BINDS_STR:
        return unsupported(node, "JoinedStr:str_shadowed")
    parts = []
    for part in node.values:
        if isinstance(part, ast.FormattedValue):
            if part.format_spec is not None:
                return unsupported(node, "JoinedStr:format_spec")
            if part.conversion == 114:
                return unsupported(node, "JoinedStr:conversion_r")
            if part.conversion == 97:
                return unsupported(node, "JoinedStr:conversion_a")
            # -1 = no conversion, 115 = `!s`, which IS `str()` spelled out.
            if part.conversion not in (-1, 115):
                return unsupported(node, "JoinedStr:conversion")
            parts.append({
                "kind": "Call",
                "span": span(part),
                "func": {"kind": "Name", "span": span(part), "id": "str"},
                "args": [convert_expr(part.value)],
                "keywords": [],
                "call_unsupported": None,
            })
        elif isinstance(part, ast.Constant) and isinstance(part.value, str):
            parts.append({
                "kind": "Constant",
                "span": span(part),
                "value": {"type": "str", "value": part.value},
            })
        else:  # not reachable from CPython's parser; loud rather than guessed
            return unsupported(node, "JoinedStr:part:" + type(part).__name__)
    if not parts:  # `f""` — no fields and no text
        return {"kind": "Constant", "span": span(node),
                "value": {"type": "str", "value": ""}}
    out = parts[0]
    for p in parts[1:]:
        out = {"kind": "BinOp", "span": span(node),
               "left": out, "op": "Add", "right": p}
    return out


def convert_expr(node):
    if isinstance(node, ast.JoinedStr):
        return convert_fstring(node)

    if isinstance(node, ast.Constant):
        v = node.value
        if v is True or v is False:  # bool before int: bool is an int subtype
            const = {"type": "bool", "value": v}
        elif isinstance(v, int):
            const = {"type": "int", "repr": str(v)}
        elif isinstance(v, str):
            const = {"type": "str", "value": v}
        elif v is None:
            const = {"type": "none"}
        else:  # float / bytes / complex / Ellipsis / ...
            return unsupported(node, "Constant:" + type(v).__name__)
        return {"kind": "Constant", "span": span(node), "value": const}

    if isinstance(node, ast.Name):
        return {"kind": "Name", "span": span(node), "id": node.id}

    if isinstance(node, ast.BinOp):
        op = type(node.op).__name__
        if op not in ALLOWED_BINOPS:
            return unsupported(node, "BinOp:" + op)
        return {
            "kind": "BinOp",
            "span": span(node),
            "left": convert_expr(node.left),
            "op": op,
            "right": convert_expr(node.right),
        }

    if isinstance(node, ast.UnaryOp):
        op = type(node.op).__name__
        if op not in ALLOWED_UNARYOPS:
            return unsupported(node, "UnaryOp:" + op)
        return {
            "kind": "UnaryOp",
            "span": span(node),
            "op": op,
            "operand": convert_expr(node.operand),
        }

    if isinstance(node, ast.BoolOp):
        return {
            "kind": "BoolOp",
            "span": span(node),
            "op": type(node.op).__name__,  # And / Or only
            "values": [convert_expr(v) for v in node.values],
        }

    if isinstance(node, ast.Compare):
        ops = [type(o).__name__ for o in node.ops]
        for op in ops:
            if op not in ALLOWED_CMPOPS:
                return unsupported(node, "Compare:" + op)
        return {
            "kind": "Compare",
            "span": span(node),
            "left": convert_expr(node.left),
            "ops": ops,
            "comparators": [convert_expr(c) for c in node.comparators],
        }

    if isinstance(node, ast.Call):
        reasons = []
        # Plain named keywords are STRUCTURED (H6); `f(**d)` unpacking
        # (a keyword node with arg=None) stays a loud call_unsupported.
        if any(kw.arg is None for kw in node.keywords):
            reasons.append("** unpacking in call")
        if any(isinstance(a, ast.Starred) for a in node.args):
            reasons.append("starred args")
        return {
            "kind": "Call",
            "span": span(node),
            "func": convert_expr(node.func),
            "args": [convert_expr(a) for a in node.args],
            "keywords": [
                {"arg": kw.arg, "value": convert_expr(kw.value)}
                for kw in node.keywords
                if kw.arg is not None
            ],
            "call_unsupported": ", ".join(reasons) if reasons else None,
        }

    if isinstance(node, (ast.List, ast.Tuple)):
        if any(isinstance(e, ast.Starred) for e in node.elts):
            # A LOAD position is a display unpacking and LOWERS.
            if isinstance(node.ctx, ast.Load):
                return lower_starred_display(node)
            # Store/Del is an assignment or `for` TARGET — position 2 of the
            # design, deliberately NOT landed. It must be refused as a WHOLE
            # node. Keeping the structural tuple (whose starred element
            # converts to `Unsupported "Starred"`) does NOT refuse: `unpackSeq`
            # checks ARITY first, so `x, *y = [1, 2, 3]` answered a FAKE
            # `ValueError: too many values to unpack (expected 2)` where
            # CPython binds `x = 1, y = [2, 3]` — MEASURED, a wrong answer
            # rather than a loud one, and fixed here.
            return unsupported(node, "Starred:target")
        return {
            "kind": type(node).__name__,
            "span": span(node),
            "elts": [convert_expr(e) for e in node.elts],
        }

    if isinstance(node, ast.Dict):
        # `{k: v, ...}` — structured (H0, docs/memory-model.md). A None key
        # is `**expansion`; keep the whole node Unsupported then.
        if any(k is None for k in node.keys):
            return unsupported(node, "Dict:unpack")
        return {
            "kind": "Dict",
            "span": span(node),
            "keys": [convert_expr(k) for k in node.keys],
            "values": [convert_expr(v) for v in node.values],
        }

    if isinstance(node, ast.IfExp):
        # `b if t else o` — structured (H5, sunfish's rotate/value use it)
        return {
            "kind": "IfExp",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": convert_expr(node.body),
            "orelse": convert_expr(node.orelse),
        }

    if isinstance(node, ast.Attribute):
        # `obj.attr` — structured (H0). Store/Del contexts arrive through
        # Assign/Delete targets; representation is context-free here.
        return {
            "kind": "Attribute",
            "span": span(node),
            "value": convert_expr(node.value),
            "attr": node.attr,
        }

    if isinstance(node, ast.Subscript):
        # CPython >= 3.9: `slice` is the index expr itself when it is a plain
        # expression; a Slice node is structured (H5 strings — sunfish's
        # `board[::-1]` / `board[:i]`); pre-3.9 ExtSlice/Index => whole node
        # Unsupported.
        sl = node.slice
        sl_kind = type(sl).__name__
        if sl_kind == "Slice":
            d = {
                "kind": "Slice",
                "span": span(node),
                "value": convert_expr(node.value),
            }
            # Components are emitted only when present in the source —
            # envelopes mirror CPython's ast (ingestion fills the absent
            # ones with `Constant None`, CPython's own BUILD_SLICE value).
            if sl.lower is not None:
                d["lower"] = convert_expr(sl.lower)
            if sl.upper is not None:
                d["upper"] = convert_expr(sl.upper)
            if sl.step is not None:
                d["step"] = convert_expr(sl.step)
            return d
        if sl_kind in ("ExtSlice", "Index"):
            return unsupported(node, "Subscript:" + sl_kind)
        return {
            "kind": "Subscript",
            "span": span(node),
            "value": convert_expr(node.value),
            "index": convert_expr(sl),
        }

    if isinstance(node, (ast.GeneratorExp, ast.ListComp)):
        # A LIST COMPREHENSION rides the same node (2026-08-13): CPython
        # compiles both into an implicit function taking the already-
        # evaluated outer iterator, differing only in what the function
        # does with each element (yield vs append) -- so the envelope
        # carries the same fields under a different `kind`, and INGESTION
        # (Json.lean) desugars `[e for x in it if c]` into
        # `list(e for x in it if c)`, which is CPython-exact and reuses
        # the genexp lowering and its capture census verbatim.
        # H4: a generator EXPRESSION is structured only in the v0 shape --
        # ONE `for` clause, not `async`. CPython compiles every genexp into
        # an implicit generator FUNCTION whose first argument is the
        # already-evaluated outer iterator, and ingestion performs exactly
        # that lowering; a multi-clause genexp is that lowering applied
        # twice, which v0 does not do, so it stays Unsupported (loud) rather
        # than half-structured. `ifs` are the clause's filters, in order.
        gens = node.generators
        if len(gens) == 1 and not getattr(gens[0], "is_async", 0):
            g = gens[0]
            # pass 7 (docs/memory-model.md §the walrus filter): a filter of
            # the EXACT shape `(v := <value>) <op> <rhs>` is emitted as the
            # rewritten filter `v <op> <rhs>` plus a `walrus` binding record
            # -- CPython's own compilation makes `v = <value>` a statement of
            # the synthesized generator body. A NamedExpr anywhere else stays
            # the generic unsupported expression (loud, never half-structured).
            walrus = []
            ifs_out = []
            for i in g.ifs:
                if (
                    isinstance(i, ast.Compare)
                    and isinstance(i.left, ast.NamedExpr)
                    and isinstance(i.left.target, ast.Name)
                    and not any(w["name"] == i.left.target.id for w in walrus)
                    and all(
                        type(o).__name__ in ALLOWED_CMPOPS for o in i.ops
                    )
                ):
                    walrus.append({
                        "name": i.left.target.id,
                        "value": convert_expr(i.left.value),
                    })
                    ifs_out.append({
                        "kind": "Compare",
                        "span": span(i),
                        "left": {
                            "kind": "Name",
                            "span": span(i.left.target),
                            "id": i.left.target.id,
                        },
                        "ops": [type(o).__name__ for o in i.ops],
                        "comparators": [convert_expr(c) for c in i.comparators],
                    })
                else:
                    ifs_out.append(convert_expr(i))
            return {
                "kind": ("ListComp" if isinstance(node, ast.ListComp)
                         else "GeneratorExp"),
                "span": span(node),
                "elt": convert_expr(node.elt),
                "target": convert_expr(g.target),
                "iter": convert_expr(g.iter),
                "ifs": ifs_out,
                "walrus": walrus,
            }
        return unsupported(node, type(node).__name__)

    return unsupported(node)


def lower_starred_display(node):
    """Lower a starred DISPLAY (docs/memory-model.md §starred displays):

        (e1, *a, e2)  ->  (e1,) + tuple(a) + (e2,)
        [e1, *a, e2]  ->  list((e1,) + tuple(a) + (e2,))
        [*a]          ->  list(tuple(a))

    Zero new node kinds, so nothing downstream moves. The obvious lowering
    `list(a) + [3]` is WRONG: `list(...)` allocates a heap object, and
    concatenation of heap objects refuses loudly — so `list(...)` appears
    only on the OUTSIDE, where a fresh list is exactly what CPython
    produces, and `tuple(...)`, the immediate-value constructor, is what
    the concatenation ever sees. Evaluation order survives: `+` associates
    left and the binOp arm binds left before right, so the pieces run in
    source order, CPython's own.

    Consecutive non-starred elements are grouped into ONE tuple display, so
    `[1, *a, 9, *a]` costs three `+`, not five.

    Inherited refusals are the reuse dividend and are deliberate: a dict or
    set receiver refuses through `tuple()`'s order doctrine, a generator
    receiver drains under the existing `moduleGenFree` guard. One honest
    mismatch, recorded rather than glossed: `[*5]` is CPython's
    `Value after * must be an iterable, not int` and the lowering raises
    `'int' object is not iterable` from `tuple()` — same exception CLASS,
    different message."""
    if _MODULE_SHADOWS_DISPLAY:
        return unsupported(node, "Starred:display_shadowed")
    parts = []
    group = []  # consecutive non-starred elements, flushed as one tuple

    def flush():
        if group:
            parts.append({
                "kind": "Tuple",
                "span": span(node),
                "elts": [convert_expr(e) for e in group],
            })
            del group[:]

    for e in node.elts:
        if isinstance(e, ast.Starred):
            flush()
            parts.append({
                "kind": "Call",
                "span": span(e),
                "func": {"kind": "Name", "span": span(e), "id": "tuple"},
                "args": [convert_expr(e.value)],
                "keywords": [],
                "call_unsupported": None,
            })
        else:
            group.append(e)
    flush()
    out = parts[0]  # non-empty: the caller found a starred element
    for p in parts[1:]:
        out = {"kind": "BinOp", "span": span(node),
               "left": out, "op": "Add", "right": p}
    if isinstance(node, ast.List):
        out = {
            "kind": "Call",
            "span": span(node),
            "func": {"kind": "Name", "span": span(node), "id": "list"},
            "args": [out],
            "keywords": [],
            "call_unsupported": None,
        }
    return out


def convert_param(p, default=None):
    """Schema ``param``. ``default`` (a const payload) is emitted only when
    present, so envelopes of default-free sources are byte-identical to the
    pre-defaults format."""
    d = {"arg": p.arg, "span": span(p)}
    if default is not None:
        d["default"] = default
    return d


def _walk_scope(fn):
    """All nodes of fn's own scope: descends the body but not into nested
    scopes (defs/lambdas/classes — Unsupported nodes in v0 anyway)."""
    stack = list(ast.iter_child_nodes(fn))
    while stack:
        node = stack.pop()
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda,
                             ast.ClassDef)):
            continue
        yield node
        stack.extend(ast.iter_child_nodes(node))


def _target_bound_names(t):
    """Names an assignment TARGET binds, per CPython's scoping rules: bare
    names bind; tuple/list/starred targets recurse; subscript/attribute
    targets bind NOTHING (``tp[k(x)] = v`` makes neither ``tp`` nor ``k``
    local — walking the whole target tree used to overapproximate here and
    falsely shadowed callees appearing inside subscript keys)."""
    if isinstance(t, ast.Name):
        return [t.id]
    if isinstance(t, (ast.Tuple, ast.List)):
        return [n for e in t.elts for n in _target_bound_names(e)]
    if isinstance(t, ast.Starred):
        return _target_bound_names(t.value)
    return []  # Subscript / Attribute: no binding


def _target_has_starred(t):
    """Does this assignment TARGET contain a star anywhere? (`a, *b`, and
    nested: `a, (b, *c)`.)

    The tier does not model starred unpacking, and `unpackSeq` already
    refuses a non-name target element — but it checks ARITY FIRST, so a
    starred target was only refused when the arity happened to coincide.
    Measured 2026-08-15 against CPython 3.9.19: `x, *y = [1,2]` refused
    loudly (correct), while `x, *y = [1,2,3]` and `*x, y = [1,2,3]`
    answered `ValueError: too many values to unpack (expected 2)` and
    `x, *y = [1]` answered `not enough values to unpack (expected 2, got 1)`
    — all three SILENT WRONG ANSWERS, where CPython binds happily. Refusing
    the whole statement at extraction restores "answers loudly or not at
    all"; it costs no coverage, because every starred target already ended
    in a refusal or a wrong answer, never in agreement.

    This is the DOCTRINE fix, not the feature: real support is designed in
    docs/backlog.md §Position 2 (a `Stmt.unpackAssign` constructor) and
    built on the `starred-displays` branch (eb6a882).
    """
    if isinstance(t, ast.Starred):
        return True
    if isinstance(t, (ast.Tuple, ast.List)):
        return any(_target_has_starred(e) for e in t.elts)
    return False


def _assigned_names(fn):
    """Names the function body assigns (CPython's static-locals rule makes
    these local THROUGHOUT the body). Params excluded."""
    names = set()
    for node in _walk_scope(fn):
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, (ast.AugAssign, ast.AnnAssign, ast.For)):
            targets = [node.target]
        elif isinstance(node, ast.Delete):
            # del RECONCILED (docs/memory-model.md paragraph "the del
            # statement", census clause 1): a `del` target is a BINDING
            # (CPython's whole-body rule localises it), which also repairs
            # the recorded disagreement with `_binding_linenos`, which
            # already counted Delete targets.
            targets = node.targets
        else:
            continue
        for t in targets:
            names.update(_target_bound_names(t))
    return names


def _del_read_names(fn):
    """`del`'d names the body also READS (docs/memory-model.md paragraph
    "the del statement", census clause 2): deliberately a NAME-SET
    intersection, never a liveness analysis -- after the removal a read
    would fall through to module globals where CPython raises
    UnboundLocalError, silently wrong, so any read of a deleted name
    refuses the whole function. The stated over-refusal
    (``x = n; del x; x = 99; return x`` refuses although CPython accepts)
    is recorded in the design. Reads in nested scopes count too -- the
    conservative direction (their capture snapshots are separately
    guarded by `_binding_linenos`, which sees the del as a binding)."""
    deleted = set()
    for node in _walk_scope(fn):
        if isinstance(node, ast.Delete):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    deleted.add(t.id)
    if not deleted:
        return []
    reads = {n.id for n in ast.walk(fn)
             if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)}
    return sorted(deleted & reads)


def _shadowed_calls(fn):
    """Called names that the body also assigns: CPython would treat the callee
    as an (initially unbound) local, so a dynamic-env interpreter cannot be
    faithful. Emitted as `locals_unsupported` so the interpreter refuses
    loudly.

    H7 refinement (the closure-escape pattern `g = _mk(a); g()`): a name
    bound EXACTLY ONCE, by a single-target plain assignment DIRECTLY in the
    body (so never inside a loop), with every call textually AFTER it, has
    no UnboundLocalError window — the dynamic env is faithful there, so it
    is not flagged."""
    assigned = _assigned_names(fn)
    hits = set()
    for node in _walk_scope(fn):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in assigned:
                hits.add(node.func.id)
    safe = set()
    for name in hits:
        linenos = _binding_linenos(fn, name)
        direct_assigns = [
            st for st in fn.body
            if isinstance(st, ast.Assign) and len(st.targets) == 1
            and isinstance(st.targets[0], ast.Name)
            and st.targets[0].id == name
        ]
        if len(linenos) == 1 and len(direct_assigns) == 1:
            ln = direct_assigns[0].lineno
            calls = [n.lineno for n in _walk_scope(fn)
                     if isinstance(n, ast.Call)
                     and isinstance(n.func, ast.Name) and n.func.id == name]
            if all(c > ln for c in calls):
                safe.add(name)
    return sorted(hits - safe)


def _has_global(node):
    """Does the whole subtree (nested scopes INCLUDED — a nested def's
    ``global`` also rebinds module names when called) contain a ``global``
    statement? Emitted on FunctionDef/ClassDef as ``"has_global": true``
    (key absent when false, keeping global-free envelopes byte-identical).
    Consumed by ingestion's namedtuple binding census: with this exact
    fact, opaque function-body statements (``try``/``with``/…) need no
    conservative refusal."""
    return any(isinstance(n, ast.Global) for n in ast.walk(node))


def _is_generator(fn):
    """Is this ``def`` a GENERATOR function? CPython's rule is purely
    syntactic and scope-local: a ``def`` whose OWN scope contains a ``yield``
    or ``yield from`` compiles to a generator, whether or not that yield is
    reachable -- calling it never runs the body, it builds a generator
    object. Unlike ``_has_global`` this must NOT descend into nested scopes:
    a nested ``def``'s yield makes the NESTED function a generator, not this
    one (``_walk_scope`` already stops at def/lambda/class boundaries)."""
    return any(isinstance(n, (ast.Yield, ast.YieldFrom)) for n in _walk_scope(fn))


def _binding_linenos(fn, name):
    """Line numbers of every statement in fn's OWN scope that BINDS `name`
    (assignment, augmented assignment, annotated assignment, `for` target,
    `del`, imports, `with … as`). Used by the H7 never-rebound-after-def
    analysis — `del` and imports count as bindings on purpose."""
    out = []
    for n in _walk_scope(fn):
        bound = []
        if isinstance(n, ast.Assign):
            for t in n.targets:
                bound += _target_bound_names(t)
        elif isinstance(n, (ast.AugAssign, ast.AnnAssign, ast.For)):
            bound += _target_bound_names(n.target)
        elif isinstance(n, ast.Delete):
            for t in n.targets:
                bound += _target_bound_names(t)
        elif isinstance(n, (ast.Import, ast.ImportFrom)):
            for al in n.names:
                bound.append((al.asname or al.name).split(".")[0])
        elif isinstance(n, ast.With):
            for item in n.items:
                if item.optional_vars is not None:
                    bound += _target_bound_names(item.optional_vars)
        if name in bound:
            out.append(n.lineno)
    return out


def _closure_analysis(nd, enclosing):
    """H7 nested defs (docs/memory-model.md §nested defs and closures):
    the capture set and the LOUD refusals of the snapshot tier.

    Captures = free names of the nested body (own scope) that are locals
    or parameters of the enclosing function — CPython's symtable rule.
    Snapshot-at-def equals CPython's cells exactly when no captured name
    is bound after the def executes; the analysis refuses (with the
    precise reason) everything outside that fragment. Returns
    ``(captures, reason_or_None)``."""
    reasons = []
    for n in ast.walk(nd):
        if n is not nd and isinstance(
                n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda,
                    ast.ClassDef)):
            reasons.append("a scope nested inside the nested def")
            break
    if any(isinstance(n, ast.Nonlocal) for n in ast.walk(nd)):
        reasons.append("nonlocal (cell writes)")
    nested_locals = {p.arg for p in list(nd.args.posonlyargs) + list(nd.args.args)}
    if isinstance(nd, ast.FunctionDef):
        nested_locals |= _assigned_names(nd)
    enclosing_params = {p.arg for p in list(enclosing.args.posonlyargs)
                        + list(enclosing.args.args)}
    # direct nested-def names are enclosing locals too (a closure may
    # capture an earlier closure — sunfish-adjacent `chain` shapes)
    def_bindings = {st.name: st.lineno for st in enclosing.body
                    if isinstance(st, ast.FunctionDef)}
    enclosing_locals = (enclosing_params | _assigned_names(enclosing)
                        | set(def_bindings))
    free = set()
    for n in _walk_scope(nd):
        if isinstance(n, ast.Name) and n.id not in nested_locals:
            free.add(n.id)
    captures = sorted(free & enclosing_locals)
    for c in captures:
        linenos = _binding_linenos(enclosing, c)
        if c in def_bindings:
            linenos = linenos + [def_bindings[c]]
        after = [ln for ln in linenos if ln > nd.lineno]
        if after:
            reasons.append(
                "captured name %r is rebound after the def (line %d) — "
                "snapshot-at-def would diverge from CPython's cell"
                % (c, min(after)))
        elif c not in enclosing_params and not [ln for ln in linenos
                                                if ln < nd.lineno]:
            reasons.append(
                "captured name %r has no binding before the def — the "
                "snapshot could miss CPython's late cell fill" % c)
    return captures, ("; ".join(reasons) if reasons else None)


def _early_nested_calls(fn):
    """Calls of a DIRECT nested-def name at a line before its def: CPython's
    static-locals rule makes the name local throughout, so such a call
    raises UnboundLocalError — a dynamic-env fallthrough to a module name
    would be silently wrong. Loud, via `locals_unsupported`."""
    defs = {st.name: st.lineno for st in fn.body
            if isinstance(st, ast.FunctionDef)}
    hits = set()
    for n in _walk_scope(fn):
        if (isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
                and n.func.id in defs and n.lineno < defs[n.func.id]):
            hits.add(n.func.id)
    return sorted(hits)


def _lambda_nested_def(node, enclosing):
    """H7 lambdas: `put = lambda board, i, p: …` DIRECTLY in a function
    body is the nested-def shape with an expression body — same snapshot
    admission, same capture analysis (a lambda body is its own scope),
    `return <expr>` as the single statement. Anything fancier (defaults
    beyond literals, *args, a nested scope inside the lambda) refuses
    through the same channels. Returns the NestedDef dict, or None when
    the assign is not this shape.

    MODULE-scope flavor (pass 3, ``enclosing=None`` — the padding loop's
    ``padrow = lambda row: …``): CPython's symtable gives a module-level
    lambda ZERO freevars — every free name in its body is a GLOBAL, read
    dynamically at call time — so the capture set is EMPTY by
    construction and the never-rebound admission is vacuous (the body's
    reads go through the live module globals at call time; docs/
    memory-model.md §module-init execution). Only a genuinely nested
    scope inside the lambda still refuses."""
    if not (isinstance(node, ast.Assign) and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(node.value, ast.Lambda)):
        return None
    lam = node.value
    name = node.targets[0].id
    a = lam.args
    plain = list(a.posonlyargs) + list(a.args)
    reasons = []
    payloads = [literal_const_payload(d) for d in a.defaults]
    if a.defaults and not all(pl is not None for pl in payloads):
        reasons.append("defaults")
        payloads = []
    first_defaulted = len(plain) - len(payloads)
    params = [
        convert_param(p, payloads[i - first_defaulted]
                      if i >= first_defaulted else None)
        for i, p in enumerate(plain)
    ]
    if a.vararg is not None:
        reasons.append("*args")
    if a.kwonlyargs:
        reasons.append("keyword-only args")
    if a.kwarg is not None:
        reasons.append("**kwargs")
    if enclosing is None:
        scope_reasons = []
        for n in ast.walk(lam):
            if n is not lam and isinstance(
                    n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda,
                        ast.ClassDef)):
                scope_reasons.append("a scope nested inside the nested def")
                break
        captures, refusal = [], ("; ".join(scope_reasons)
                                 if scope_reasons else None)
    else:
        captures, refusal = _closure_analysis(lam, enclosing)
    out = {
        "kind": "NestedDef",
        "span": span(node),
        "name": name,
        "args": params,
        "args_unsupported": ", ".join(reasons) if reasons else None,
        "locals_unsupported": None,
        "body": [{"kind": "Return", "span": span(lam.body),
                  "value": convert_expr(lam.body)}],
        "captures": captures,
        "closure_unsupported": refusal,
    }
    return out


def convert_stmt(node, enclosing=None, module_scope=False,
                 import_guard=False):
    # `import_guard` (Pass 0, docs/memory-model.md paragraph "Import
    # forms (Pass 0)"): True exactly when `node` is a DIRECT body
    # statement of a `try` whose single handler is `except ImportError:`
    # (set by the Try arm below and deliberately NOT threaded into
    # nested if/loop bodies -- a nested statement is not in guard
    # position, because the guard argument is "the raise is caught by
    # construction", which only the direct body gives).
    # pass 3: a module-scope single-target `name = lambda …` assign (top
    # level, or directly in a top-level for/while/if body) is the
    # NestedDef shape with ZERO captures (module-scope flavor above)
    if module_scope:
        nd = _lambda_nested_def(node, None)
        if nd is not None:
            return nd
    if isinstance(node, ast.FunctionDef):
        a = node.args
        plain = list(a.posonlyargs) + list(a.args)
        reasons = []
        # Positional defaults: LITERAL defaults (int/bool/str/None Constant)
        # are in-tier — emitted as a "default" const payload on the trailing
        # params (a.defaults aligns with the tail of posonly+args, per
        # CPython). Any NON-literal default (a Name like easter's
        # EASTER_WESTERN, a negative number, a call, a mutable [] / {}) keeps
        # the whole function at args_unsupported: "defaults" with no
        # "default" keys emitted — refused loudly at call time, as before.
        payloads = [literal_const_payload(d) for d in a.defaults]
        if a.defaults and not all(p is not None for p in payloads):
            reasons.append("defaults")
            payloads = []
        first_defaulted = len(plain) - len(payloads)
        params = [
            convert_param(p, payloads[i - first_defaulted]
                          if i >= first_defaulted else None)
            for i, p in enumerate(plain)
        ]
        if a.vararg is not None:
            reasons.append("*args")
        if a.kwonlyargs:
            reasons.append("keyword-only args")
        if a.kwarg is not None:
            reasons.append("**kwargs")
        if node.decorator_list:
            reasons.append("decorators")
        out = {
            "kind": "FunctionDef",
            "span": span(node),
            "name": node.name,
            "args": params,
            "args_unsupported": ", ".join(reasons) if reasons else None,
            "locals_unsupported": (
                "calls locally-assigned name(s) (static-locals rule): "
                + ", ".join(shadowed)
                if (shadowed := _shadowed_calls(node))
                else (
                    "calls nested-def name(s) before the def (static-locals "
                    "rule): " + ", ".join(early)
                    if (early := _early_nested_calls(node))
                    else (
                        # del census clause 2 (docs/memory-model.md
                        # paragraph "the del statement")
                        "reads del'd name(s) (a dynamic-env fallthrough "
                        "to a module name would be silently wrong): "
                        + ", ".join(delread)
                        if (delread := _del_read_names(node))
                        else None
                    )
                )
            ),
            # a nested def DIRECTLY in this body is the H7 closure shape
            # (a single-target `name = lambda …` assign likewise); one
            # nested deeper (inside an if/loop) stays a plain
            # FunctionDef/Lambda node, which ingestion refuses loudly
            "body": [_lambda_nested_def(s, node) or convert_stmt(s, enclosing=node)
                     for s in node.body],
        }
        if _has_global(node):
            out["has_global"] = True
        if _is_generator(node):
            out["is_generator"] = True
        if node.decorator_list:
            # THE THIRD DOOR (docs/memory-model.md §class semantics, "Class
            # CREATION is an effect"): `args_unsupported` already carries
            # "decorators", but it is a comma-joined MESSAGE that also
            # carries "*args"/"defaults"/"**kwargs" -- none of which is a
            # creation effect. Ingestion needs the decorator fact ALONE, as
            # a structured flag in the has_global/is_generator family, to
            # re-check a class body's creation purity without matching on
            # prose.
            out["has_decorators"] = True
        if enclosing is not None:
            # H7 (docs/memory-model.md §nested defs and closures): a def
            # DIRECTLY inside a function body is structured as NestedDef,
            # with the capture set and the snapshot tier's refusals
            captures, refusal = _closure_analysis(node, enclosing)
            out["kind"] = "NestedDef"
            out["captures"] = captures
            out["closure_unsupported"] = refusal
        return out

    if isinstance(node, ast.ClassDef):
        # Structured (H3, docs/memory-model.md). The interpreter owns the
        # tier boundary, but features that change what a DEFINITION means
        # (bases/metaclass/decorators, class-level statements binding class
        # attributes) are flagged here, like args_unsupported: the class is
        # represented, instantiation refuses loudly.
        reasons = []
        namedtuple_base = None
        exception_base = False
        if node.bases:
            # A SINGLE base that is a plain `namedtuple(...)` call is the
            # recorded value-like subclass shape (sunfish's Position):
            # emitted structurally as `namedtuple_base` (ingestion
            # validates the spec and the module census; on any failure the
            # class demotes to the ordinary uninstantiable-loudly state).
            # A SINGLE base literally named `Exception` over a body of
            # only pass/docstring (no methods), with no keywords and no
            # decorators, is the exceptions tier's exact recognized shape
            # (`class Stop(Exception): pass`) -- emitted as
            # `exception_base`; ingestion's census may still demote it.
            # Any other base keeps the loud inheritance reason.
            b = node.bases[0]
            if (len(node.bases) == 1 and isinstance(b, ast.Call)
                    and isinstance(b.func, ast.Name)
                    and b.func.id == "namedtuple" and not b.keywords):
                namedtuple_base = convert_expr(b)
            elif (len(node.bases) == 1 and isinstance(b, ast.Name)
                    and b.id == "Exception"
                    and not node.keywords and not node.decorator_list
                    and all(isinstance(s, ast.Pass)
                            or (isinstance(s, ast.Expr)
                                and isinstance(s.value, ast.Constant))
                            for s in node.body)):
                exception_base = True
            else:
                reasons.append("bases (inheritance)")
        if node.keywords:
            reasons.append("class keywords (metaclass)")
        if node.decorator_list:
            reasons.append("decorators")
        for s in node.body:
            if isinstance(s, ast.FunctionDef):
                continue
            if isinstance(s, ast.Pass):
                continue
            if isinstance(s, ast.Expr) and isinstance(s.value, ast.Constant):
                continue  # docstring / stray constant
            reasons.append("class-level statements (class attributes)")
            break
        # CREATION EFFECTS, structured separately from the tier reasons
        # above: does executing the `class` statement itself do anything
        # OBSERVABLE (print, raise, call)? CPython evaluates the bases and
        # runs the body there; the model builds its ClassDefn at ingestion
        # and executes nothing, so anything effectful here would be
        # silently skipped. An UNDECORATED method, `pass`, docstrings and
        # LITERAL attribute bindings are invisible; a call, a name read, an
        # unrecognized base, a metaclass keyword or a decorator is not.
        #
        # THE THIRD DOOR (2026-08-14, found by harness/class_census.py):
        # a DECORATED method is an effect too, and this loop used to skip
        # every `FunctionDef` unconditionally. `@log def m(self)` calls
        # `log` AT the `class` statement -- CPython prints, the model
        # executed no class body and printed nothing: a wrong answer, not
        # a refusal, through the one door the flag did not check. Measured
        # over the pinned 3.9 Lib: 15 such classes in 14 files, 2 of them
        # in files this admission passed. Every one decorates with
        # property/setter/classmethod/staticmethod, which happen to have
        # no creation-time effect -- lucky, not sound.
        creation_effects = bool(node.keywords) or bool(node.decorator_list)
        if node.bases and namedtuple_base is None and not exception_base:
            creation_effects = True
        for s in node.body:
            if isinstance(s, ast.FunctionDef):
                if s.decorator_list:
                    creation_effects = True
                    break
                continue
            if isinstance(s, ast.Pass):
                continue
            if isinstance(s, ast.Expr) and isinstance(s.value, ast.Constant):
                continue
            if (isinstance(s, ast.Assign) and isinstance(s.value, ast.Constant)
                    and all(isinstance(t, ast.Name) for t in s.targets)):
                continue
            creation_effects = True
            break
        out = {
            "kind": "ClassDef",
            "span": span(node),
            "name": node.name,
            "class_unsupported": ", ".join(reasons) if reasons else None,
            "creation_effects": creation_effects,
            "body": [convert_stmt(s) for s in node.body],
        }
        if namedtuple_base is not None:
            out["namedtuple_base"] = namedtuple_base
        if exception_base:
            out["exception_base"] = True
        if _has_global(node):
            out["has_global"] = True
        return out

    if isinstance(node, ast.Return):
        return {
            "kind": "Return",
            "span": span(node),
            "value": convert_expr(node.value) if node.value is not None else None,
        }

    if isinstance(node, ast.Assign):
        if any(_target_has_starred(t) for t in node.targets):
            # Refuse the STATEMENT, not just the starred element: the model
            # arity-checks a tuple target before it inspects the elements,
            # so an inner `Unsupported` leaf was reached too late and a
            # wrong ValueError escaped. See `_target_has_starred`.
            return unsupported(node, "Starred:target")
        return {
            "kind": "Assign",
            "span": span(node),
            "targets": [convert_expr(t) for t in node.targets],
            "value": convert_expr(node.value),
        }

    if isinstance(node, ast.AugAssign):
        op = type(node.op).__name__
        if op not in ALLOWED_BINOPS:
            return unsupported(node, "AugAssign:" + op)
        return {
            "kind": "AugAssign",
            "span": span(node),
            "target": convert_expr(node.target),
            "op": op,
            "value": convert_expr(node.value),
        }

    if isinstance(node, ast.While):
        return {
            "kind": "While",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": [convert_stmt(s, module_scope=module_scope) for s in node.body],
            "orelse": [convert_stmt(s, module_scope=module_scope) for s in node.orelse],
        }

    if isinstance(node, ast.For):
        # Plain `for` only; `async for` is a different node class
        # (ast.AsyncFor) and falls through to Unsupported.
        return {
            "kind": "For",
            "span": span(node),
            "target": convert_expr(node.target),
            "iter": convert_expr(node.iter),
            "body": [convert_stmt(s, module_scope=module_scope)
                     for s in node.body],
            "orelse": [convert_stmt(s, module_scope=module_scope)
                       for s in node.orelse],
        }

    if isinstance(node, ast.If):
        return {
            "kind": "If",
            "span": span(node),
            "test": convert_expr(node.test),
            "body": [convert_stmt(s, module_scope=module_scope) for s in node.body],
            "orelse": [convert_stmt(s, module_scope=module_scope) for s in node.orelse],
        }

    if isinstance(node, ast.Assert):
        # The tail batch (docs/memory-model.md paragraph "the assert
        # statement"): structured as test + optional message. CPython
        # compiles this to `if not test: raise AssertionError(msg)` under
        # `__debug__`; evaluation owns the tier boundary (the message must
        # be renderable, and it is evaluated ONLY on the failing path).
        d = {"kind": "Assert", "span": span(node), "test": convert_expr(node.test)}
        if node.msg is not None:
            d["msg"] = convert_expr(node.msg)
        return d
    if isinstance(node, ast.Delete):
        # The tail batch (docs/memory-model.md paragraph "the del
        # statement"): BARE NAMES only -- `del d[k]`, `del o.attr`,
        # `del xs[i]` are measured second tables and keep the Unsupported
        # fallthrough (census clause 4). Both scopes are structured: the
        # function-scope tier is the recorded census (clauses 1-2 above),
        # the module-scope tier is the script executor's arm plus the
        # trailing-del-of-defs ingestion rewrite (docs/backlog.md
        # paragraph "del RECONCILED with the one pipeline" -- the revised
        # clause 3).
        if all(isinstance(t, ast.Name) for t in node.targets):
            return {"kind": "Delete", "span": span(node),
                    "names": [t.id for t in node.targets]}
        return unsupported(node)
    if isinstance(node, ast.Raise):
        # Exceptions tier (docs/memory-model.md paragraph "exceptions"):
        # structured in FULL generality -- bare raise, raise <expr>,
        # raise ... from ... all parse; evaluation owns the tier boundary
        # (only `raise N` of an admitted exception class is admitted).
        d = {"kind": "Raise", "span": span(node)}
        if node.exc is not None:
            d["exc"] = convert_expr(node.exc)
        if node.cause is not None:
            d["cause"] = convert_expr(node.cause)
        return d

    if isinstance(node, ast.Try):
        # Exceptions tier: the v0 single-handler shape is carried
        # structurally (exc_name + handler body); every out-of-v0 feature
        # fills try_unsupported (the call_unsupported pattern), and
        # execution refuses with the reason -- structured-but-loud. The
        # body/handler are carried best-effort either way so the Lean-side
        # censuses (binds/refs/yield/def walkers) stay exact.
        reasons = []
        exc_name = ""
        handler_body = []
        if len(node.handlers) != 1:
            reasons.append("multiple handlers" if node.handlers
                           else "no handler")
        else:
            h = node.handlers[0]
            if h.type is None:
                reasons.append("bare 'except:'")
            elif isinstance(h.type, ast.Name):
                exc_name = h.type.id
            else:
                reasons.append("non-name handler class "
                               "(tuple pattern / attribute)")
            if h.name is not None:
                reasons.append("'as' binding")
            handler_body = [convert_stmt(s, module_scope=module_scope)
                            for s in h.body]
        if node.orelse:
            reasons.append("'else' clause")
        if node.finalbody:
            reasons.append("'finally' clause")
        # Pass 0 (docs/memory-model.md paragraph "Import forms
        # (Pass 0)"): a top-level try whose single handler is literally
        # `except ImportError:` puts its DIRECT body statements in
        # import-guard position -- the fifth admission conjunct of the
        # ImportFrom arm below. The guard is decided on the handler
        # NAME alone; a try that is otherwise out of v0 (an `as`
        # binding, `finally`, ...) still carries `try_unsupported` and
        # refuses WHOLE at execution, before any guarded import inside
        # it could run -- loud, never wrong.
        guard = (module_scope and len(node.handlers) == 1
                 and isinstance(node.handlers[0].type, ast.Name)
                 and node.handlers[0].type.id == "ImportError")
        return {
            "kind": "Try",
            "span": span(node),
            "body": [convert_stmt(s, module_scope=module_scope,
                                  import_guard=guard)
                     for s in node.body],
            "exc_name": exc_name,
            "handler": handler_body,
            "try_unsupported": ", ".join(reasons) if reasons else None,
        }

    if isinstance(node, ast.Expr) and isinstance(node.value, ast.YieldFrom):
        # pass 5: `yield from e` in STATEMENT position -- structured
        # (schema `YieldFrom`); ingestion INLINES the admitted genexp
        # shape into `for target in it: yield elt` (docs/memory-model.md
        # section "yield from") and everything un-lowered refuses loudly
        # at execution. Expression-position `yield from` (a delegation
        # RESULT consumer) keeps falling through to Unsupported below.
        return {"kind": "YieldFrom", "span": span(node),
                "value": convert_expr(node.value.value)}

    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Yield):
        # H4: `yield e` in STATEMENT position -- the only yield the tier
        # admits (a yield in EXPRESSION position receives a `send` value and
        # stays loudly out, so it keeps falling through to Unsupported).
        # A bare `yield` emits no "value" key; ingestion fills `Constant
        # None`, CPython's own compilation -- the `Slice` convention.
        d = {"kind": "Yield", "span": span(node)}
        if node.value.value is not None:
            d["value"] = convert_expr(node.value.value)
        return d

    if isinstance(node, ast.Expr):
        return {"kind": "Expr", "span": span(node), "value": convert_expr(node.value)}

    if isinstance(node, ast.Pass):
        return {"kind": "Pass", "span": span(node)}
    if isinstance(node, ast.Break):
        return {"kind": "Break", "span": span(node)}
    if isinstance(node, ast.Continue):
        return {"kind": "Continue", "span": span(node)}

    if isinstance(node, ast.ImportFrom):
        # Pass 0 (docs/memory-model.md paragraph "Import forms
        # (Pass 0)"): STRUCTURE exactly the paying shape -- module top
        # level, absolute (level == 0), single unqualified module name,
        # plain names or star, no `as` aliases -- AND one of:
        #   * the module is ABSENT from the pinned platform inventory
        #     (the Pass 0 raise is then CPython's own behavior,
        #     guarded or not);
        #   * the exact benign-whitelist texts (BENIGN_IMPORT_FROM
        #     above), structured here and canonicalized back to the
        #     legacy Unsupported node at ingestion;
        #   * import-guard position (a direct body statement of a
        #     top-level `try` with a single `except ImportError:`
        #     handler -- the raise is caught by construction and the
        #     PURE FALLBACK runs) AND the accelerator carries a PASSING
        #     entry in ACCELERATOR_ADMISSIONS above. That registry is the
        #     memo's differential obligation made checkable
        #     (docs/c-intrinsics-proposal.md 2.5): no entry, no
        #     admission, and the refusal names which of the two it is.
        # EVERYTHING else -- relative, dotted, aliased, non-top-level,
        # and the unguarded from-import of a platform-present module --
        # keeps the Unsupported fallthrough below VERBATIM. The
        # extractor is the envelope's trust boundary (the `py_kind`/
        # `exception_base`/`has_global` precedents), so the Lean side
        # needs no inventory: its Pass 0 semantics raises
        # unconditionally, and this admission is what makes that raise
        # faithful.
        star = len(node.names) == 1 and node.names[0].name == "*"
        if (module_scope and node.level == 0 and node.module is not None
                and "." not in node.module
                and all(a.asname is None for a in node.names)
                and (star or all(STEM_RE.match(a.name) is not None
                                 for a in node.names))):
            admitted = (unparse_truncated(node) in BENIGN_IMPORT_FROM
                        or node.module not in platform_inventory())
            if not admitted and import_guard:
                record = ACCELERATOR_ADMISSIONS.get(node.module)
                if record is None:
                    return unsupported(node, "ImportFrom:accelerator-unmeasured")
                if not record["equivalent"]:
                    return unsupported(node, "ImportFrom:accelerator-diverges")
                admitted = True
            if admitted:
                out = {
                    "kind": "ImportFrom",
                    "span": span(node),
                    "module": node.module,
                    "names": [] if star else [a.name for a in node.names],
                }
                if star:
                    out["star"] = True
                return out

    return unsupported(node)


# ---------------------------------------------------------------------------
# lean[ block scanner
# ---------------------------------------------------------------------------

def strip_comment_marker(line):
    """Strip the leading ^\\s*# and at most one following space.

    Lines inside a block that do not carry a comment marker (e.g. blank lines)
    are kept verbatim.
    """
    m = COMMENT_PREFIX_RE.match(line)
    if m is None:
        return line
    rest = line[m.end():]
    if rest.startswith(" "):
        rest = rest[1:]
    return rest


def scan_lean_blocks(lines, path):
    """Return [{"first_line": ..., "last_line": ..., "text": ...}, ...].

    first_line/last_line are the 1-based line numbers of the `# lean[` and
    `# ]` marker lines. text is the joined inner lines, comment markers
    stripped, no trailing newline. Unclosed block => ExtractError.
    """
    blocks = []
    i = 0
    n = len(lines)
    while i < n:
        if LEAN_OPEN_RE.match(lines[i]):
            first_line = i + 1
            j = i + 1
            inner = []
            while j < n and not LEAN_CLOSE_RE.match(lines[j]):
                inner.append(strip_comment_marker(lines[j]))
                j += 1
            if j >= n:
                raise ExtractError(
                    "%s:%d: unclosed '# lean[' block (no matching '# ]')"
                    % (path, first_line)
                )
            blocks.append(
                {"first_line": first_line, "last_line": j + 1, "text": "\n".join(inner)}
            )
            i = j + 1
        else:
            i += 1
    return blocks


# ---------------------------------------------------------------------------
# Companion generation
# ---------------------------------------------------------------------------

def pascal_case(stem):
    """my_func -> MyFunc (split on '_', uppercase first letter of each part)."""
    return "".join(p[:1].upper() + p[1:] for p in stem.split("_"))


AUTOGEN_MARKER = "AUTOGENERATED by extractors/python/extract.py"


def header_lines(source_rel, source_sha256):
    """The companion's AUTOGENERATED header.

    Default form: a Lean block comment (kept byte-identical to the historical
    format so unchanged sources regenerate byte-stably). But the source path
    is embedded verbatim, and inside ``/- … -/`` a path containing ``/-``
    opens a *nested* block comment (resp. ``-/`` closes the header early) —
    the companion then dies with "unterminated comment" at EOF. Such paths
    (e.g. scratch roots with dash-leading segments) switch the whole header
    to ``--`` line comments, where both sequences are inert.
    """
    if "/-" in source_rel or "-/" in source_rel:
        return [
            "-- " + AUTOGEN_MARKER + " — DO NOT EDIT.",
            "-- source: " + source_rel,
            "-- sha256: " + source_sha256,
        ]
    return [
        "/-",
        AUTOGEN_MARKER + " — DO NOT EDIT.",
        "source: " + source_rel,
        "sha256: " + source_sha256,
        "-/",
    ]


def check_companion_overwritable(companion_path):
    """Hard error unless companion_path is absent or extractor-generated
    (AUTOGENERATED marker within its first three lines — where both header
    forms carry it). Never silently clobber a hand-written .lean file."""
    if not os.path.exists(companion_path):
        return
    try:
        with open(companion_path, "r", encoding="utf-8", errors="replace") as f:
            head = f.read(512)
    except OSError as e:
        raise ExtractError("%s: cannot read existing companion: %s"
                           % (companion_path, e))
    if not any(AUTOGEN_MARKER in ln for ln in head.split("\n")[:3]):
        raise ExtractError(
            "%s: refusing to overwrite — the existing file lacks the "
            "AUTOGENERATED header (hand-written?). Move it aside or pass a "
            "different --companion-dir." % companion_path
        )


def generate_companion(stem, source_rel, json_rel, source_sha256, blocks):
    hoisted = []  # deduped, order-preserving across all blocks
    block_bodies = []
    for b in blocks:
        body_lines = []
        for ln in b["text"].split("\n") if b["text"] != "" else []:
            if ln.startswith("import "):
                if ln not in hoisted:
                    hoisted.append(ln)
            else:
                body_lines.append(ln)
        block_bodies.append("\n".join(body_lines))

    parts = header_lines(source_rel, source_sha256) + [
        "import LeanModels",
    ]
    parts.extend(hoisted)
    parts.append("")
    parts.append("open LeanModels LeanModels.Python")
    parts.append("")
    parts.append('load_program %s from "%s"' % (stem, json_rel))
    for body in block_bodies:
        if body.strip() == "":
            continue  # block contained only imports (or nothing)
        parts.append("")
        parts.append(body)
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def rel_posix(path):
    """Normalize a user-supplied path for use inside emitted files."""
    return os.path.normpath(path).replace(os.sep, "/")


def process_file(source_path, companion_dir, out=None):
    """Extract one source. ``out`` (leanpy's arbitrary-file mode) redirects
    the envelope to a directory or an explicit ``.json`` path; without it the
    envelope lands next to the source, as every in-tree example expects."""
    stem = os.path.splitext(os.path.basename(source_path))[0]
    if out is None and not STEM_RE.match(stem):
        raise ExtractError(
            "%s: stem %r is not a valid identifier (must match ^[A-Za-z_][A-Za-z0-9_]*$)"
            % (source_path, stem)
        )

    try:
        with open(source_path, "rb") as f:
            data = f.read()
    except OSError as e:
        raise ExtractError("%s: cannot read: %s" % (source_path, e))

    source_sha256 = hashlib.sha256(data).hexdigest()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as e:
        raise ExtractError("%s: not valid UTF-8: %s" % (source_path, e))

    try:
        tree = ast.parse(text, filename=source_path)
    except SyntaxError as e:
        raise ExtractError("%s: syntax error: %s" % (source_path, e))

    blocks = scan_lean_blocks(text.splitlines(), source_path)

    # The two lowerings' shadow censuses (see `binds_any_name`): both are
    # whole-module, so both are decided once, here, before any expression
    # is converted.
    global _MODULE_BINDS_STR, _MODULE_SHADOWS_DISPLAY
    _MODULE_BINDS_STR = binds_any_name(tree, FSTRING_LOWERING_NAMES)
    _MODULE_SHADOWS_DISPLAY = binds_any_name(tree, DISPLAY_LOWERING_NAMES)

    source_rel = rel_posix(source_path)
    json_rel = os.path.splitext(source_rel)[0] + ".json"

    envelope = {
        "schema_version": SCHEMA_VERSION,
        "language": "python",
        "frontend": {"name": FRONTEND["name"], "version": FRONTEND["version"]},
        "source_file": source_rel,
        "source_sha256": source_sha256,
        "module": {"kind": "Module",
                   "body": [convert_stmt(s, module_scope=True)
                            for s in tree.body]},
        "lean_blocks": blocks,
    }

    if out is None:
        json_path = os.path.splitext(source_path)[0] + ".json"
    elif out.endswith(".json"):
        json_path = out
    else:
        json_path = os.path.join(out, stem + ".json")
    parent = os.path.dirname(json_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(envelope, f, indent=2)
        f.write("\n")

    if not blocks:
        # Pure source (three-file per-example layout): envelope only. The
        # spec/proof .lean files are hand-written siblings, never generated.
        return

    if not STEM_RE.match(stem):
        raise ExtractError(
            "%s: stem %r is not a valid identifier (must match ^[A-Za-z_][A-Za-z0-9_]*$), "
            "so the '# lean[' blocks have no companion name" % (source_path, stem)
        )
    if companion_dir is None:
        # Default: the companion lives next to its source (per-example
        # directory layout — Examples/python/sum_to/sum_to.py → Examples/python/sum_to/).
        companion_dir = os.path.dirname(source_path) or "."
    companion_path = os.path.join(companion_dir, pascal_case(stem) + ".lean")
    check_companion_overwritable(companion_path)
    companion_text = generate_companion(stem, source_rel, json_rel, source_sha256, blocks)
    os.makedirs(companion_dir, exist_ok=True)
    with open(companion_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(companion_text)


def main(argv=None):
    sys.setrecursionlimit(10000)
    parser = argparse.ArgumentParser(
        prog="extract.py",
        description="Extract Python sources to envelope JSON + Lean companion files "
        "(run from the repo root).",
    )
    parser.add_argument("sources", nargs="+", metavar="file.py")
    parser.add_argument(
        "--companion-dir",
        default=None,
        help="directory for generated companion .lean files "
        "(default: the source file's own directory)",
    )
    parser.add_argument(
        "--out",
        default=None,
        metavar="DIR_OR_FILE.json",
        help="write the envelope here instead of next to the source "
        "(leanpy's arbitrary-file mode); an explicit .json path is allowed "
        "only with a single source",
    )
    args = parser.parse_args(argv)

    if args.out is not None and args.out.endswith(".json") and len(args.sources) > 1:
        print("error: --out <file.json> takes a single source (got %d)" % len(args.sources),
              file=sys.stderr)
        return 1

    try:
        for src in args.sources:
            process_file(src, args.companion_dir, args.out)
    except ExtractError as e:
        print("error: %s" % e, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
