/-
Examples/system-verilog/popcnt — CV32E40P phase-2 acceptance (sv-0.2).

  cv32e40p_popcnt.sv.json — symbolic envelope of OpenHW CV32E40P
                            `rtl/cv32e40p_popcnt.sv` (checkout
                            6033d2b1be3295ec774d17ac4cf226faacfdeb08),
                            regenerated byte-identically by
      python3.12 extractors/sv/extract.py --top cv32e40p_popcnt \
          rtl/include/cv32e40p_pkg.sv rtl/include/cv32e40p_apu_core_pkg.sv \
          rtl/include/cv32e40p_fpu_pkg.sv rtl/cv32e40p_popcnt.sv \
          -o cv32e40p_popcnt.sv.json
  ingest.lean             — THIS FILE: the T-select acceptance twin of
                            `ff_one/ingest.lean` for the parameter-LESS
                            popcount adder tree (census: `popcount = sum
                            of bits via adder tree at W=32 — concrete`).

Passed `PDesign.crossCheck` at load (the load-time differential against
slang's `resolved` metadata; a mismatch refuses the load).

What the pins certify:
* zero SV parameters → zero binders: `cv32e40p_popcnt : Design` directly;
* the four generate-for levels of the adder tree expand structurally to
  31 processes (16+8+4+2 slice assigns + the final `result_o` add);
* the design is FULLY in-tier under the semantic tier (`Design2`): no
  unsupported node survives instantiation — first real-core module with
  nothing left out;
* `run2` reproduces the simulator-verified popcount rows (the
  differential harness case `popcnt` in `harness/sv/cases2.json`, green
  vs **Xcelium and Icarus** on the identical RTL source), including the
  4-state row: one x bit in the input x-poisons the count through the
  adder tree.
-/
import LeanModels.Sv.Ingest2
import LeanModels

namespace Examples.«system-verilog».popcnt.ingest

open LeanModels.Sv

load_design_sv2 cv32e40p_popcnt from "Examples/system-verilog/popcnt/cv32e40p_popcnt.sv.json"

/-! ## The (degenerate) family surface -/

-- No SV parameters, no localparams: the family is a single point.
#guard cv32e40p_popcnt.pdesign.params == []
#guard cv32e40p_popcnt.pdesign.localParams == []

-- Ports + the four adder-tree levels; widths of the narrowing tree.
#guard cv32e40p_popcnt.pdesign.declSig ==
  [("in_i", true, false), ("result_o", false, true), ("cnt_l1", false, false),
   ("cnt_l2", false, false), ("cnt_l3", false, false), ("cnt_l4", false, false)]
#guard (cv32e40p_popcnt.pdesign.instantiate []).toOption.map
        (fun d => d.decls.map fun dc => (dc.name, dc.width))
      == some #[("in_i", 32), ("result_o", 6), ("cnt_l1", 32), ("cnt_l2", 24),
                ("cnt_l3", 16), ("cnt_l4", 10)]

-- The starter lemma consumes the loaded design, ∀ args ∀ fuel.
example {args : List Int} {F : Nat} {m : Design}
    (h : cv32e40p_popcnt.pdesign.instantiate args F = .ok m) : m.WFNames :=
  instantiate_WFNames h (by decide)

/-! ## Phase-2 acceptance: fully in-tier, executes end-to-end -/

-- 31 processes (the four generate-for levels + the final add), and NO
-- unsupported node survives — the whole file is inside the semantic tier.
#guard (cv32e40p_popcnt.pdesign.instantiate2 []).toOption.map
        (fun d => (d.processes.size, d.hasUnsupported)) == some (31, false)

-- Harness case `popcnt` CYCLE 0–6 (dual-simulator-verified): popcount of
-- 0, 2^32−1, 0xA5A5A5A5, 2^31, 2^16, 7 — and the 4-state row: a single
-- x bit x-poisons the whole count through the adder tree.
private def pcIn (v : Nat) : SvState := [("in_i", LVec.ofNat 32 v)]

#guard (Res.toOption (run2 (cv32e40p_popcnt.pdesign.instantiateD2 []) σ_src 2000
        [pcIn 0, pcIn 0xFFFFFFFF, pcIn 0xA5A5A5A5, pcIn 0x80000000,
         pcIn 0x00010000, pcIn 7,
         [("in_i", LVec.lit "0000000000000000000000000000000x")]])).map
        (fun tr => tr.map fun st => SvState.showSignal st "result_o")
      == some ["000000", "100000", "010000", "000001", "000001", "000011",
               "xxxxxx"]

end Examples.«system-verilog».popcnt.ingest
