/-
AUTOGENERATED by extractors/python/extract.py — DO NOT EDIT.
source: Examples/tut_03/tut_03.py
sha256: 372e3dd4b4a5d2e25607256ca971ff406b88e090e5526ee17b299fc149f29364
-/
import LeanModels

open LeanModels LeanModels.Python

load_program tut_03 from "Examples/tut_03/tut_03.json"

/-! Tutorial 03 (docs/tutorial/03-branching-and-preconditions.md):
hypotheses as preconditions, branching, and reading goal states. -/
#py_check tut_03.relu(5) = 5
#py_check tut_03.relu(-5) = 0
#py_check tut_03.relu(0) = 0

/-- Unconditional total correctness: `py_prove` splits the symbolic
branch left by `if x < 0:` and closes both arms with `omega` (which
knows `max`). -/
theorem relu_total (x : PyInt) : tut_03.relu(x) ==> max x 0 := by
  py_prove [tut_03]

/-- With a precondition, the spec simplifies: on nonnegative inputs
`relu` is the identity. A precondition is an ordinary named hypothesis —
but `py_prove` (unlike `py_begin`) does not restate `Py*`-branded
hypotheses for `omega`, so the `have` line re-lands `hx` at `Int` first
(docs/tutorial/06-when-proofs-fail.md, failure mode 5). -/
theorem relu_of_nonneg (x : PyInt) (hx : 0 ≤ x) : tut_03.relu(x) ==> x := by
  have hx' : (0 : Int) ≤ x := hx
  py_prove [tut_03]

/-- The same theorem with the proof spelled out, for reading goal states
(docs/tutorial/03-branching-and-preconditions.md walks through each
step's goal). -/
theorem relu_of_nonneg' (x : PyInt) (hx : 0 ≤ x) : tut_03.relu(x) ==> x := by
  have hx' : (0 : Int) ≤ x := hx
  refine ⟨32, ?_⟩
  py_simp [callFunction, tut_03]
  split <;> py_simp
  omega

/-! Delaborator regression (LeanModels/Python/Delab.lean): statements
print back in surface notation. -/

/-- info: relu_total (x : PyInt) : tut_03.relu(x) ==> max x 0 -/
#guard_msgs in
#check relu_total
