/-
Examples/system-verilog/ff_one — CV32E40P phase-2 ingestion smoke (sv-0.2).

  cv32e40p_ff_one.sv.json — symbolic envelope of OpenHW CV32E40P
                            `rtl/cv32e40p_ff_one.sv` (checkout
                            6033d2b1be3295ec774d17ac4cf226faacfdeb08),
                            regenerated byte-identically by
      python3.12 extractors/sv/extract.py --top cv32e40p_ff_one \
          rtl/include/cv32e40p_pkg.sv rtl/include/cv32e40p_apu_core_pkg.sv \
          rtl/include/cv32e40p_fpu_pkg.sv rtl/cv32e40p_ff_one.sv \
          -o cv32e40p_ff_one.sv.json
  ingest.lean             — THIS FILE: `load_design_sv2` smoke. The ∀-LEN
                            crown-jewel spec (`docs/cv32e40p-spec-surface.md`
                            entry 1) lands with the T-select tier phase; this
                            file certifies the parametric pipeline under it.

`load_design_sv2` already gated this envelope through `PDesign.crossCheck`
(our defaults elaboration vs slang's `resolved` metadata — the load-time
differential): a mismatch would refuse the load and fail this file.

What the pins below certify, at two parameter points of ONE family:
* binder encoding: `cv32e40p_ff_one : (LEN : Nat) → Design` (declaration
  order; `NUM_LEVELS` is a localparam, computed — NOT a binder);
* symbolic widths: `first_one_o` = `$clog2(LEN)`, `sel_nodes` = `2^NUM_LEVELS`,
  `index_lut` = multi-dim `LEN × NUM_LEVELS` bits;
* generate families expand structurally: 97 processes at LEN=32,
  25 at LEN=8 (3 module-level + index LUT loop + selection tree);
* the port surface is parameter-independent (`instantiate_declSig`
  consumed on the loaded design, plus executable pins);
* out-of-tier constructs stay LOUD: the generate bodies assign to
  `sel_nodes[...]` (T-select tier), so every M0 run is `.unsupported` —
  never a silently wrong value.
-/
import LeanModels.Sv.Ingest2
import LeanModels

namespace Examples.«system-verilog».ff_one.ingest

open LeanModels.Sv

load_design_sv2 cv32e40p_ff_one from "Examples/system-verilog/ff_one/cv32e40p_ff_one.sv.json"

/-! ## The family surface -/

-- One SV parameter → one Nat binder, declaration order.
#guard cv32e40p_ff_one.pdesign.params.map (·.name) == ["LEN"]
-- `NUM_LEVELS = $clog2(LEN)` is a localparam: computed at instantiation,
-- not a binder.
#guard cv32e40p_ff_one.pdesign.localParams.map (·.name) == ["NUM_LEVELS"]
#guard cv32e40p_ff_one.pdesign.localParams.map (·.expr)
        == [.sysCall .clog2 (.paramRef "LEN" none)]

-- The declaration surface (names + directions) is parameter-independent
-- (executable face of `instantiate_declSig`).
#guard cv32e40p_ff_one.pdesign.declSig ==
  [("in_i", true, false), ("first_one_o", false, true), ("no_ones_o", false, true),
   ("index_lut", false, false), ("sel_nodes", false, false), ("index_nodes", false, false)]
#guard (cv32e40p_ff_one 32).inputNames == #["in_i"]
#guard (cv32e40p_ff_one 32).outputNames == #["first_one_o", "no_ones_o"]

-- … and the lemma itself consumes the loaded design, ∀ args ∀ fuel.
example {args : List Int} {F : Nat} {m : Design}
    (h : cv32e40p_ff_one.pdesign.instantiate args F = .ok m) : m.WFNames :=
  instantiate_WFNames h (by decide)

/-! ## Two parameter points of one family -/

-- LEN = 32 (the core's instantiation): first_one_o is $clog2(32) = 5 bits,
-- sel_nodes 2^5 = 32, index_lut 32×5 = 160 (multi-dim packed = one vector).
#guard (cv32e40p_ff_one 32).decls.map (fun d => (d.name, d.width)) ==
  #[("in_i", 32), ("first_one_o", 5), ("no_ones_o", 1),
    ("index_lut", 160), ("sel_nodes", 32), ("index_nodes", 160)]

-- LEN = 8: 3 / 8 / 24 — same family, nothing re-extracted.
#guard (cv32e40p_ff_one 8).decls.map (fun d => (d.name, d.width)) ==
  #[("in_i", 8), ("first_one_o", 3), ("no_ones_o", 1),
    ("index_lut", 24), ("sel_nodes", 8), ("index_nodes", 24)]

-- Generate expansion is structural and parameter-dependent: the index-LUT
-- loop contributes LEN processes, the selection tree 2·(2^NUM_LEVELS − 1).
#guard (cv32e40p_ff_one 32).processes.size == 97   -- 3 + 32 + 62
#guard (cv32e40p_ff_one 8).processes.size == 25    -- 3 + 8 + 14

/-! ## Loudness ledger (the honest part)

The generate bodies read and WRITE `sel_nodes[...]`/`index_nodes[...]` —
select expressions and select targets, the T-select tier. The envelope now
carries them as `BitSel`/`PartSel` nodes (semantic-tier sv-0.2 growth),
the **M0** `Design` still refuses them loudly (`T2:*` in-design nodes),
and the **semantic tier** (`Design2`, next section) executes them. -/

#guard (cv32e40p_ff_one 32).hasUnsupported
#guard run (cv32e40p_ff_one 32) σ_src 256 [[("in_i", LVec.ofNat 32 4)]]
        == .unsupported "unsupported process 'T2:AssignL'"
#guard run (cv32e40p_ff_one 8) σ_src 256 [[("in_i", LVec.ofNat 8 4)]]
        == .unsupported "unsupported process 'T2:AssignL'"

-- Bad parameters are loud, never wrong.
#guard cv32e40p_ff_one.pdesign.instantiate []
        == .unsupported "parameter arity: got 0, want 1"

/-! ## Phase-2 acceptance: the envelope EXECUTES under the semantic tier

`instantiate2` lowers the same `pdesign` into `Design2` — fully in-tier
(no unsupported nodes survive), and `run2` reproduces the simulator-
verified traces. Every row below replays a cycle of the differential
harness cases `ff_one_len8`/`ff_one_len32` (`harness/sv/cases2.json`),
green vs **Xcelium and Icarus** on the identical RTL source. -/

#guard (cv32e40p_ff_one.pdesign.instantiate2 [8]).toOption.map
        (·.hasUnsupported) == some false
#guard (cv32e40p_ff_one.pdesign.instantiate2 [32]).toOption.map
        (·.hasUnsupported) == some false

-- ff_one_len8 CYCLE 0–5: first_one_o = lowest set bit index; the
-- all-zero input drives no_ones_o and parks first_one_o at all-ones.
#guard (Res.toOption (run2 (cv32e40p_ff_one.pdesign.instantiateD2 [8]) σ_src 2000
        [[("in_i", LVec.ofNat 8 4)], [("in_i", LVec.ofNat 8 0)],
         [("in_i", LVec.ofNat 8 1)], [("in_i", LVec.ofNat 8 0x80)],
         [("in_i", LVec.ofNat 8 0xFF)], [("in_i", LVec.ofNat 8 0xA0)]])).map
        (fun tr => tr.map fun st =>
          (SvState.showSignal st "first_one_o", SvState.showSignal st "no_ones_o"))
      == some [("010", "0"), ("111", "1"), ("000", "0"),
               ("111", "0"), ("000", "0"), ("101", "0")]

-- ff_one_len32 CYCLE 3: the top bit at LEN = 32 — same family, no
-- re-extraction, 97 expanded processes.
#guard (Res.toOption (run2 (cv32e40p_ff_one.pdesign.instantiateD2 [32]) σ_src 2000
        [[("in_i", LVec.ofNat 32 0x80000000)]])).map
        (fun tr => tr.map fun st =>
          (SvState.showSignal st "first_one_o", SvState.showSignal st "no_ones_o"))
      == some [("11111", "0")]

end Examples.«system-verilog».ff_one.ingest
