#!/usr/bin/env bash
# tools/backlog-index.sh — GENERATE docs/backlog/INDEX.md from the per-lane
# files, because §9.5 says the index is generated and never hand-maintained.
#
# §9.5's own words: "`docs/backlog.md` becomes a GENERATED index, which is
# §5.5's 'generated and checked, never hand-maintained' applied to the
# repository's own record."  This is that generator.
#
# The monolith it replaces collided with itself — `L2`, `L3` and `L4` each
# appear TWICE — because every lane appended to one tail at ~66 landings a
# day.  Per-lane files remove the collision; an index puts the single view
# back without putting the contention back.
#
# USAGE
#   tools/backlog-index.sh              # write docs/backlog/INDEX.md
#   tools/backlog-index.sh --stdout     # print it, write nothing
#   tools/backlog-index.sh --check      # regenerate and DIFF: exit 1 on drift
#   tools/backlog-index.sh --self-test
#
# EXIT  0 in sync (or written)   1 drift (--check)   2 refusal
#
# ZERO Lean execution.  Safe outside a tenure (A11).

set -u

CLONE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR=""
MODE="write"

usage() { sed -n '1,/^set -u/p' "${BASH_SOURCE[0]}" >&2; exit 2; }
die()   { echo "backlog-index.sh: $*" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)       CLONE="${2:-}"; shift 2 ;;
    --backlog)   DIR="${2:-}"; shift 2 ;;
    --stdout)    MODE="stdout"; shift ;;
    --check)     MODE="check"; shift ;;
    --self-test) MODE="self-test"; shift ;;
    -h|--help)   usage ;;
    *)           die "unknown argument '$1'" ;;
  esac
done
[ -n "$DIR" ] || DIR="$CLONE/docs/backlog"

# One row per `## ` heading.  The id is the first token; everything after the
# first em dash is the title.  A heading that is not a dated id is REPORTED,
# not skipped — §9.5's scheme is `YYYY-MM-DD-<lane>-<n>`, and a drifter that
# is quietly dropped is a row nobody sees is missing.
rows() {                        # -> "sortkey\tid\ttitle\tlane"
  local f base
  for f in "$DIR"/*.md; do
    [ -f "$f" ] || continue
    base="$(basename "$f")"
    case "$base" in INDEX.md) continue ;; esac
    awk -v lane="${base%.md}" '
      /^## / {
        line = substr($0, 4)
        id = line; sub(/[ \t].*$/, "", id)
        title = line
        if (index(title, " — ") > 0) sub(/^[^—]*— */, "", title)
        else sub(/^[^ ]+ */, "", title)
        gsub(/\r/, "", title)
        # `YYYY-MM-DD-<lane>-<n>` -> a key that sorts by date then NUMBER.
        if (id ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}-.*-[0-9]+$/) {
          date = substr(id, 1, 10)
          n = id; sub(/^.*-/, "", n)
          key = sprintf("%s %04d", date, n)
        } else {
          key = "0000-00-00 0000"      # undated: sorts LAST, and is flagged
        }
        printf "%s\t%s\t%s\t%s\n", key, id, title, lane
      }' "$f"
  done
}

render() {
  local total lanes undated
  total="$(rows | grep -c .)"
  lanes="$(rows | awk -F'\t' '{print $4}' | sort -u | grep -c .)"
  undated="$(rows | awk -F'\t' '$1 ~ /^0000/' | grep -c .)"
  cat <<HDR
# The backlog INDEX — every lane's entries, newest first

**GENERATED by \`tools/backlog-index.sh\`. Do not hand-edit.** §9.5 makes the
index generated rather than maintained, which is §5.5's *"generated and
checked, never hand-maintained"* applied to the repository's own record.

Entries live in \`docs/backlog/<lane>.md\`, appended only by their own lane,
with ids \`YYYY-MM-DD-<lane>-<n>\` that need no reservation. Everything before
the split is in [\`docs/backlog-archive.md\`](../backlog-archive.md), frozen,
and every existing \`§Lnn\` reference still resolves there.

**$total entries across $lanes lanes.** Regenerate with
\`tools/backlog-index.sh\`; check with \`--check\` (exit 1 on drift).

| id | title | lane |
| --- | --- | --- |
HDR
  rows | LC_ALL=C sort -r | awk -F'\t' '{ printf "| `%s` | %s | %s |\n", $2, $3, $4 }'
  if [ "$undated" != "0" ]; then
    printf '\n**%s heading(s) do not use the §9.5 id scheme** and sort last.\n' "$undated"
  fi
}

# --------------------------------------------------------------- self-test
if [ "$MODE" = "self-test" ]; then
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/blindex-selftest.XXXXXX")" || die "no temp dir"
  trap 'rm -rf "$tmp"' EXIT
  ok=0; bad=0
  check() { if [ "$2" = "$3" ]; then ok=$((ok+1)); echo "  ok   $1"; \
            else bad=$((bad+1)); echo "  FAIL $1: got '$2' want '$3'"; fi; }

  mkdir -p "$tmp/bl"
  DIR="$tmp/bl"
  cat > "$tmp/bl/alpha.md" <<'MD'
# The alpha lane
## 2026-08-20-alpha-1 — the first thing
body
## 2026-08-22-alpha-2 — the second thing
body
MD
  cat > "$tmp/bl/beta.md" <<'MD'
# The beta lane
## 2026-08-21-beta-1 — a beta thing
## 2026-08-22-beta-10 — the TENTH, which must outrank the second
MD

  check "every entry becomes a row"    "$(rows | grep -c .)" "4"
  check "the lane comes from the FILE" "$(rows | awk -F'\t' '$2=="2026-08-21-beta-1"{print $4}')" "beta"
  check "the title is the em-dash tail" "$(rows | awk -F'\t' '$2=="2026-08-20-alpha-1"{print $3}')" "the first thing"
  # The trap a lexicographic sort walks into: `-10` must beat `-2`.
  check "newest first, and 10 > 2 NUMERICALLY" \
        "$(rows | LC_ALL=C sort -r | head -1 | awk -F'\t' '{print $2}')" "2026-08-22-beta-10"
  check "  ...with the same-day sibling next" \
        "$(rows | LC_ALL=C sort -r | sed -n 2p | awk -F'\t' '{print $2}')" "2026-08-22-alpha-2"
  check "the oldest sorts last" \
        "$(rows | LC_ALL=C sort -r | tail -1 | awk -F'\t' '{print $2}')" "2026-08-20-alpha-1"

  # An UNDATED heading is flagged, never dropped.
  printf '## G1 — an undated drifter\n' >> "$tmp/bl/beta.md"
  check "a drifter still yields a row"   "$(rows | grep -c .)" "5"
  check "  ...and is flagged in the page" "$(render | grep -c 'do not use the §9.5 id scheme')" "1"
  check "  ...and sorts LAST"             "$(rows | LC_ALL=C sort -r | tail -1 | awk -F'\t' '{print $2}')" "G1"
  sed -i.bak '$d' "$tmp/bl/beta.md"; rm -f "$tmp/bl/beta.md.bak"

  check "the page counts entries and lanes" "$(render | grep -c '\*\*4 entries across 2 lanes\.\*\*')" "1"
  check "the page says GENERATED"           "$(render | grep -c 'GENERATED by')" "1"
  check "INDEX.md is not its own input"     "$(printf '# x\n## 2026-01-01-x-1 — x\n' > "$tmp/bl/INDEX.md"; rows | grep -c .)" "4"

  # §5.4's double-run clause, on the generator.
  check "double run is byte-identical" \
        "$( [ "$(render | shasum | cut -d' ' -f1)" = "$(render | shasum | cut -d' ' -f1)" ] && echo same)" "same"

  # --check must FAIL on drift and pass in sync: both directions (MEAS-42).
  render > "$tmp/bl/INDEX.md"
  check "in sync, --check is quiet"  "$(diff -q <(render) "$tmp/bl/INDEX.md" >/dev/null && echo insync)" "insync"
  printf '\nhand-edited\n' >> "$tmp/bl/INDEX.md"
  check "drifted, --check notices"   "$(diff -q <(render) "$tmp/bl/INDEX.md" >/dev/null && echo insync)" ""

  echo "self-test: $ok ok, $bad failed"
  [ "$bad" = "0" ] || exit 1
  exit 0
fi

[ -d "$DIR" ] || die "no backlog directory at '$DIR'"
OUT="$DIR/INDEX.md"

case "$MODE" in
  stdout) render ;;
  check)
    if [ ! -f "$OUT" ]; then
      echo "backlog-index.sh: DRIFT — $OUT does not exist; run tools/backlog-index.sh" >&2
      exit 1
    fi
    if render | diff -q - "$OUT" >/dev/null 2>&1; then
      echo "backlog-index.sh: in sync ($(rows | grep -c .) entries)"
    else
      echo "backlog-index.sh: DRIFT — $OUT is stale; run tools/backlog-index.sh" >&2
      render | diff - "$OUT" | head -12 >&2
      exit 1
    fi ;;
  write)
    render > "$OUT" || die "cannot write '$OUT'"
    echo "backlog-index.sh: wrote $OUT ($(rows | grep -c .) entries)" ;;
esac
