/-
AUTOGENERATED by extractors/python/extract.py — DO NOT EDIT.
source: Examples/tut_02/tut_02.py
sha256: e8bc4d683548c563939830517275e2ea5faf7828ab0d40c2d88672405065dfd9
-/
import LeanModels

open LeanModels LeanModels.Python

load_program tut_02 from "Examples/tut_02/tut_02.json"

/-! Tutorial 02 (docs/tutorial/02-first-spec.md): the `==>` arrow and
`py_prove` on straight-line code. -/
#py_check tut_02.square(5) = 25
#py_check tut_02.square(-4) = 16
#py_check tut_02.square(0) = 0

/-- Total correctness: `square(x)` terminates and returns `x * x`, for
every Python int `x`. One tactic; no `Val`, no fuel, no AST in sight. -/
theorem square_total (x : PyInt) : tut_02.square(x) ==> x * x := by
  py_prove [tut_02]

/-- Whatever `square(x)` returns equals `x * x` — the relational reading,
via the hypothesis-position arrow `⇓` and determinism-modulo-fuel
(`CallsTo.typed_int_eq`, Surface.lean). -/
theorem square_result (x r : PyInt) (h : tut_02.square(x) ⇓ r) : r = x * x :=
  CallsTo.typed_int_eq h (square_total x)

/-- Squares are nonnegative — once `square_result` pins the result, the
rest is ordinary mathematics with ordinary Lean tools; the interpreter
never reappears. -/
theorem square_nonneg (x r : PyInt) (h : tut_02.square(x) ⇓ r) : 0 ≤ r := by
  rw [square_result x r h]
  rcases Int.le_total 0 x with hx | hx
  · exact Int.mul_nonneg hx hx
  · have := Int.mul_nonneg (a := -x) (b := -x) (by omega) (by omega)
    rwa [Int.neg_mul_neg] at this
